### ISSUE TITLE
Failed to load Line 5 unknown rule type <!DOCTYPE

### ISSUE THREAD

**Issue by fljsdbd** [NeverSinkDev/NeverSink-Filter#10]
Hi, i have been loaded twice with 4.23 and 4.24 version. Both are failed and said like this " Line 5 unknown rule type <!DOCTYPE", can you fix this please?

**Comment by fljsdbd** [comment]
I was using the regular version.

**Comment by fljsdbd** [comment]
nevermind, i was so dummy and downloaded from the code webiste directly..

**Comment by danidoedel** [comment]
I guess you can close the issue then.

**Comment by NeverSinkDev** [comment]
Closed
