### ISSUE TITLE
Feature request: (RE)Set certain part of the filter

### ISSUE THREAD

**Issue by deduijk** [NeverSinkDev/NeverSink-Filter#100]
It would be nice if you could 'reset' part of the filter to a certain filter preset.

Use-case:
I made a custom version of the uber strict plus filter that works for me., but during leveling i would like to use the normal filter.
Currently applying the save file to the filter the filter sets to uber strict plus.

It would be great if you could like select a preset per section; like leveling u can select normal for and for end game u can select uber strict plus.

Also when loading a save file you could maybe select per section if it gets imported? (so when i load the save file; the filter let's you select if you want to apply the save file to certain sections).

The last 1 isn't needed if you can 'reset' certain sections of the filter (after applying the save file).

**Comment by NeverSinkDev** [comment]
I'm afraid this feature is very niche and can cause a large number of conflicts: such as misbehaviour of overrides, higher save-file complexity and break dependencies in a save-file.

We might add more support for similar features in the future, but currently I see more harm than good and a lot of development overhead. While it's not ideal, most of these things can be done by hand as of right now in the customize screen.
