### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by PJP2810** [NeverSinkDev/NeverSink-Filter#101]
Small thing that I'd love to seed added purely for OCD reasons. With version numbering would it be worth adding the 0 for 6.60 for example, as Windows doesn't understand that v5.6 comes after v5.43 for example due to Windows being stupid

**Comment by danidoedel** [comment]
How is that stupid? It‘s just not how maths or version numbering is working. 6 is obvious smaller than 43.

**Comment by PJP2810** [comment]
I fully understand what you're saying, however that does not change the fact that it isn't how the version numbering is being implemented here.

If you check the past releases you'll notice that

V6.34->6.4->6.5->6.51->6.6->6.65->6.65a->6.65b

So, before trying to claim there is not implied 0, there clearly is by the author. Thus my point remains that it would be useful for that implied 0 to be added to the version number instead of being ommited.

**Comment by NeverSinkDev** [comment]
Sounds good.
Addressed in 7.00 ;)
