### ISSUE TITLE
T0 divination cards lost when auto-sorting

### ISSUE THREAD

**Issue by m1ckswagger** [NeverSinkDev/NeverSink-Filter#103]
My guess is that House of Mirrors and The Immortal are just so rare in hardcore league that they do not even show up on poe.ninja. So when high-lighting and auto-sorting divination cards based on any trade site these divination cards dont get any value assigned and hence removed from T0 category.

I know I can add them manually. But is it possible to exclude cards without a value from the sorting process and leave them in the tier they were assigned to.

Would just be kind of sad if someone misses these drops because they only activated valuable divination cards.

**Comment by Tobnac** [comment]
Fixed!
