### ISSUE TITLE
Personal Item Progression -> Class undefined

### ISSUE THREAD

**Issue by itsamemarkus** [NeverSinkDev/NeverSink-Filter#106]
I wanted to edit my leveling filter to highlight claws and 1h swords, The initial preset works for *Personal Item Progression 1* but afaik you can't add another *Personal Item Progression 2* because class is undefined.

![2019-03-08 17_40_58-window](https://user-images.githubusercontent.com/34944988/54042107-a55bce80-41c9-11e9-9b8d-1896208f63be.png)

(Thanks for the update and hard work)

**Comment by NeverSinkDev** [comment]
We fixed this a few minutes ago. Just reload the site! :)
