### ISSUE TITLE
Allow modifying preset settings after changes have been applied

### ISSUE THREAD

**Issue by vith** [NeverSinkDev/NeverSink-Filter#107]
Couldn't the user's customizations be stored separately from the effects of the presets and be reapplied on top of any preset setting change?

Having to start from scratch every time I want to change a preset setting gets tedious.

**Comment by Tobnac** [comment]
I dont think this would be compatible with how the current save/load system works.

Lets say a user starts with some currency preset and then adds some custom rare rules manually.
Then, they decide to edit the presets and add the chaos recipe preset.

This would then cause a conflict:
The preset says "create 5 custom rules. set newCustomRule1 to helmets, 2 to wands, etc..."
Then, we load the previous customization from the user, which says e.g. "create 1 custom rule, set newCustomRule 1 to gloves, ...". This would then interfere with the preset and cause unintentional and simply wrong results.

I see your problem, but its hard to know/analyze what exactly the user has done and how to correctly merge that into the preset.
