### ISSUE TITLE
6 Socket fractured items does not play any drop sound

### ISSUE THREAD

**Issue by husjon** [NeverSinkDev/NeverSink-Filter#110]
Using the current latest commit: 38f2a11687861bc7fd1bb4b453d0e2ed4097645e

There are no sounds on 6 socket fractured items (see: https://youtu.be/_GJeHp1UBEs for reference).

I am using the Very Strict filter, however this affects all of them.

**Comment by NeverSinkDev** [comment]
Addressed in 7.0, thanks
