### ISSUE TITLE
2 Disabled Divination Cards are Filtered for

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#112]
When I meticulously combed through all Divination cards in the game I noticed this filter lists 2 of the 5 disabled ones:

"Birth of the Three"
"Dying Anguish"

Nothing major but thought you might like to know.

**Comment by Tobnac** [comment]
This doesn't really matter, but keeping them tiered doesn't hurt anyone and in case they somehow start dropping again, they're already handled. The 3 other disabled ones were probably worthless and not directly tiered and handled via the "All remaining DivCards"-Tier (tier 4)
