### ISSUE TITLE
Command builder doesn't work on PlayEffect

### ISSUE THREAD

**Issue by NessunoRAWRS** [NeverSinkDev/NeverSink-Filter#114]
Selecting PlayEffect on all filters won't find out anything.
Trying out on a brand new filter:
![image](https://user-images.githubusercontent.com/3737504/59121047-51db5700-8957-11e9-9bb1-c53693ecb77f.png)

![image](https://user-images.githubusercontent.com/3737504/59120964-193b7d80-8957-11e9-8707-5b3d6978672a.png)

Furthemore setting the negated effect, even on Temp, results in 566 entries:
![image](https://user-images.githubusercontent.com/3737504/59121140-89e29a00-8957-11e9-987b-f1ce81dea18a.png)

But it doesn't actually apply any change.

This is the first time ever i tried using this feature on beams.
Available for more infos, gladly, if even needed.

**Comment by Tobnac** [comment]
Thanks for letting us know! There was a problem with the optional Temp parameter. We just fixed this locally and will push it to the live server with the next update - probably later today.
