### ISSUE TITLE
Elder 6S - no drop sound

### ISSUE THREAD

**Issue by weilharter** [NeverSinkDev/NeverSink-Filter#115]
An Elder 6S doesn't trigger the "6S Drop" or any sound effect at all

**Comment by NeverSinkDev** [comment]
As of right now, this is something I can't fix easily, due to the internal mechanics of a POE filter - in a way, I'm comfortable with.

Luckily this is such a rare occurrence and has such trivial impact upon a players income, that this is not a major issue.

Still thank you for your report
