### ISSUE TITLE
Hide rares by Tier

### ISSUE THREAD

**Issue by Jivonchi** [NeverSinkDev/NeverSink-Filter#117]
I tried the option 'Hide T1 and worse tiers, excluding jewelry and 83-86 crafting items' but it does not hide normal rares such as tricone, corsair, mind cage and such even at level 70 zone. Needed to manually hide them in the handpicked base option.

**Comment by Jivonchi** [comment]
![Annotation 2019-06-14 180307](https://user-images.githubusercontent.com/41033861/59501796-dc2f3800-8ece-11e9-8331-fe761b80984c.png)

![Annotation 2019-06-14 180307](https://user-images.githubusercontent.com/41033861/59501775-d33e6680-8ece-11e9-9c7c-81c8ab7b7449.png)

**Comment by Tobnac** [comment]
Thanks for letting us know! We just fixed the rule (+Overview for rares) locally and will deploy this with the next update, probably in a few hours.
