### ISSUE TITLE
Fractal Thoughts Wrong Tier By a Lot Now

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#119]
Maybe there's been a shift in the meta (based on poe.ninja values seems like), but Unique Vaal Mask Fractal Thoughts isn't tiered properly now.
https://poe.ninja/challenge/unique-armours/fractal-thoughts-vaal-mask

**Comment by NeverSinkDev** [comment]
I've addressed this in the latest patch.
