### ISSUE TITLE
Where Do You Catch Abyss Uniques?

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#120]
I must be blind because I can't see anywhere that you filter Bubonic Trail/Tombfist/Shroud of the Lightless/Lightpoacher (Murder Boots/Steelscale Gauntlets/Carnal Armour/Great Crown). Even 1-socket variants on some can be 8-10c, and 2-socket up to 5-7ex. Are they triaged outside the unique items block somehow?

**Comment by NeverSinkDev** [comment]
I can't check the amount of abyss sockets in the filter. In addition those only drop from a boss. So they don't receive any major highlight.
