### ISSUE TITLE
Failed to load filter

### ISSUE THREAD

**Issue by tertle** [NeverSinkDev/NeverSink-Filter#125]
![image](https://user-images.githubusercontent.com/6189147/66248869-6564c600-e76f-11e9-81ea-2d8b7f111942.png)

You can see the filter here: http://filterblade.xyz/Profile?name=tertle

It was added to filter after an auto sort on HC

**Comment by Tobnac** [comment]
This was an error in the data from poeNinja. They fixed it again just now.

**Comment by tertle** [comment]
This is not fixed btw

**Comment by Tobnac** [comment]
How? You need to reset or auto-sort the unique tiers again to remove the wrong items and re-download the filter, but the corrupted data is no longer in FilterBlade itself.

**Comment by tertle** [comment]
When I posted that I did do an auto sort from hardcore of the uniques again on a new filter, and they were still added.

![image](https://user-images.githubusercontent.com/6189147/66267127-2e7ad700-e879-11e9-9b46-35233d43e09c.png)

However I have just tried again and it seems fixed so not sure what was up.
