### ISSUE TITLE
How to shift the ilvl of leveling items?

### ISSUE THREAD

**Issue by IThoughtYouKnow** [NeverSinkDev/NeverSink-Filter#126]
_First of all, I want to apologize for asking my question through the GitHub issues._

Making my first league build i most often farm some currency by doing chaos recipe on blood aqueduct. So i have a problem with shifting items ilvl limit from:
•_leveling(below lvl 65)_ to _leveling(below lvl 60)_
•_endgame(65+)_ to  _endgame(60+)_

**Comment by NeverSinkDev** [comment]
This is sadly not an easy problem. For that you need to edit every Itemlevel >= 65 to ItemLevel >= 60 and everything under it to the reversed value. This affects over a hundred rules and needs constant up-to-date checks, so I don't offer it as a built-in function on FilterBlade.

This **can** however be be manually implemented via www.FilterBlade.xyz command builder (on the advanced screen), but you need to be careful and double check the outcome.

Create the command:
Select rules with Rarity = Rare and ItemLevel >= 65 and set the action to ItemLevel >= 60

Closed, as this is not an issue.
