### ISSUE TITLE
Sorcerer Boot T1 unique

### ISSUE THREAD

**Issue by ryan-andri** [NeverSinkDev/NeverSink-Filter#127]
https://ibb.co/34hdcks
Steppan Eard boot is currently 1c in league/non league.
Loot filter: Neversink - Uberstrict

**Comment by Norky** [comment]
Skyforth is also a unique Sorcerer's Boot. https://poe.ninja/standard/unique-armours/skyforth-sorcerer-boots  It is currently 40c in Blight league and 1ex in Standard league (what do you mean by "non-league"?)

**Comment by NeverSinkDev** [comment]
I agree, with their current pricing, they should be in the milti base tier, not the T1 area. 

The reason this is currently happening is that my algorithm i use to adjust pricing currently treats steppan eard as a league only, boss only unique, which kind of treats it's frequency as too low.

I'll adjust that for 3.9
