### ISSUE TITLE
Additional Armour-Type-Based Rule Strictness

### ISSUE THREAD

**Issue by JusKillmeQik** [NeverSinkDev/NeverSink-Filter#128]
At the very bottom of the customize page you can setup Additional Show/Hide Rules. All of the Rules have a strictness that I guess could be updated, but the one I care about is Armour-Type-Based. The lowest Strictness you can add is "Only override all leveling rules". I would like to be able to "Don't override any rules". The reason for this is that I set up the colors I want in the leveling section. I then set the armour types that I could chrome into the colors I need. However, the armour type rules over write the specific color rules. So all of my items that are Energy Shield based look the same, whether they have my color group yet or not. Ideally I would see all of the Energy Shield based items, but the ones with my colors already on them would pop and leave an icon for me to go back to.

**Comment by NeverSinkDev** [comment]
We intend to rework the additional rules sections.

However, as of now I recommend using the "add additional rules" in the leveling section, since you have more power to decide what to override there.
