### ISSUE TITLE
Early League Unique and Metamorph Visibility

### ISSUE THREAD

**Issue by livejamie** [NeverSinkDev/NeverSink-Filter#129]
Hey NeverSink, just a friendly suggestion.

The Early Game Unique color is nearly identical with the Metamorph Samples/Atlas Watchstones

Example:
![image](https://user-images.githubusercontent.com/49513/70854856-60f71080-1e76-11ea-9648-2a8d0ca3a9d3.png)

I almost didn't pick these up. :)

![image](https://user-images.githubusercontent.com/49513/70854866-9dc30780-1e76-11ea-9244-27583e140f18.png)

I'd recommend a contrasting color between these two, thanks!

**Comment by NeverSinkDev** [comment]
Fixed, my choice of colors for early league predictions was really not a great one.
