### ISSUE TITLE
Wrong textcolor for normal "Superior Highland Blade" 6 sockets 17 quality

### ISSUE THREAD

**Issue by ColdFaith** [NeverSinkDev/NeverSink-Filter#13]
Hi, 
as you can see in the attched picture the textcolor is wrong for the item. It shows that it is a rare item, but it is a normal white item. 

![1](https://cloud.githubusercontent.com/assets/24418813/20941279/039a49a6-bbf6-11e6-8c22-a38c96e357bd.png)

**Comment by tswierkot** [comment]
This happened to me also, with a 6 socket 75 ilvl body armour.

**Comment by NeverSinkDev** [comment]
Fixed in 4.4. Thank you
