### ISSUE TITLE
Having an issue loading the filter

### ISSUE THREAD

**Issue by nrennstimpy** [NeverSinkDev/NeverSink-Filter#130]
Hello, 

I'm currently trying to load the filter, but am getting this error message:

Line 1909: Unable to parse parameter for Class rule: No tem classes matching "Warstaff"

I get this any time I load the game or try to load a different strictness. I've followed the directions from filterblade to download and install the filter correctly, but am I missing something?

**Comment by Damiein** [comment]
I get the same message

**Comment by Tobnac** [comment]
This is the exact error message you would get when using an old version of the filter because GGG changed the Warstaff class name with 3.9. I can confirm that this word is not anywhere in FilterBlade, so I recommend you tripple check the download, the PoE folder and the selected filter inGame.

**Comment by nrennstimpy** [comment]
But I’ve downloaded the latest version and ensured it’s set to the correct folder. I’ve also followed the exact steps from the filter blade site, yet still ran into this error. What am I missing?

**Comment by Tobnac** [comment]
You can open the filter in a text editor and search for the word "Warstaff" in it. If the filter you get from FilterBlade contains the word, try clearing your browser cache or try a different browser. If not, then the game is using another/older filter file.

**Comment by NeverSinkDev** [comment]
You're using an outdated version.

You either copied the wrong file, downloaded the wrong file, some security settings might block the copy/overwrite, but there's no way around that.
