### ISSUE TITLE
NeverSink and filterblade issue

### ISSUE THREAD

**Issue by dubcat** [NeverSinkDev/NeverSink-Filter#131]
When you download NeverSink from filterblade.
"Maelström Staff" get cut into "Maelstr"
I guess it has something to do with filterblades encoding ?

**Comment by NeverSinkDev** [comment]
Yeah. 

We struggled for some time to find an encoding setup that supports all browsers and doesn't cause any bugs. This failed several times, eventually we hack-fixed the issue.

**Comment by NeverSinkDev** [comment]
However, as of right now I don't see this causing any damage. So unless there will be further need to improve the situation, it'll stay the same for now.
