### ISSUE TITLE
Impossibility to edit high level craft bases.

### ISSUE THREAD

**Issue by IThoughtYouKnow** [NeverSinkDev/NeverSink-Filter#133]
You can't directly edit a rule in "castomize>Endgame-general(lvl65+)>high level rules"
![изображение](https://user-images.githubusercontent.com/42166757/71432425-544fa380-2725-11ea-959f-373d907a6b76.png)

But you can edit same rules in simulate section.
![изображение](https://user-images.githubusercontent.com/42166757/71432504-e2c42500-2725-11ea-8906-c18b0de782de.png)

Is this a bug or a feature?

**Comment by NeverSinkDev** [comment]
It is possible. Scroll down, it has multiple appearances attached to it.

The whole section is a bit confusing and will be reworked at some point.
