### ISSUE TITLE
Rare i84, Level 1 Base Item "Plank Kite Shield" not Hidden (Semi-Strict)

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#135]
Shows up both when it was unidentified, and after I identified it.

![image](https://user-images.githubusercontent.com/14173022/72015889-795d0f80-3217-11ea-8a8d-953de5902b64.png)

**Comment by NeverSinkDev** [comment]
Found the problem. It's super niche, but I'll see if I can fix it, thanks!
