### ISSUE TITLE
[Feature Request] Auto sort all

### ISSUE THREAD

**Issue by Firedrops** [NeverSinkDev/NeverSink-Filter#136]
About once a week I go back to FilterBlade and auto-sort things according to economy prices. Would be great if this could be sped up with one "auto sort all" kind of button.

Subrequests:
1. A way to exclude certain sections from this "auto sort all" button.
2. A way to detect and remember manually re-tiered items to be immune from "auto sort all" button. Some items are heavily price fixed, requiring manual re-tiering.

**Comment by NeverSinkDev** [comment]
A way to exclude certain sections from autosorting is already in filterblade under the tiering configuration: https://imgur.com/a/JDO107u

We also have a nearly finished protoype for "locking" basetypes and sections, which allows you to override filter update changes as well.

However, as for the full-auto-sorting, I have some good and some bad news:

1) Good: it already exists. Kinda. When you select the filter, on the frontpage, you can use the "economy-updated" versions. These update every 4 hours and are *way* more sophisticated in their tiering, than what filterblade auto-tiering offers. However, the algorithm is not customizable.
2) Bad: While we might add auto-sort on load... It's unlikely we'll do it anytime soon, there's some technical limitations and we'd need to significantly rework several sections to get it to work right, so it's not a huge priority.
