### ISSUE TITLE
Changes from Regular/Strict apply to each other

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [NeverSinkDev/NeverSink-Filter#137]
When trying to edit Strict and Regular, they share the settings. So Strict is always the same as regular.

**Comment by NeverSinkDev** [comment]
I have no idea what you're implying. Please provide some details.

**Comment by AkumaNoTsubasa** [comment]
When I edit anything on a regular filter like not-hiding the hidable uniques it applies to strict too. If I then re-hide the hidable uniques on strict it hides them on regular too.

**Comment by NeverSinkDev** [comment]
Well... yes. No bug here.

If you're doing it on FilterBlade and using "download all strictnesses" or just switch the strictness via drop down, it transfers the changes. If you don't want that, use the reset button or reload the site.

**Comment by AkumaNoTsubasa** [comment]
How is that not a bug ?
Until now you could switch strictnesses freely. Why would you transfer changes from one strictness to the other? How would I be able to make a change on strict, remember to make a change on standard and then change something on very strict ?

**Comment by NeverSinkDev** [comment]
I assume you're talking about filterblade here, not about text editors.

The behaviour was always the same. Unless you hit "reset", all changes are transferred. Use reset and separate saves to keep the changes split up.

**Comment by AkumaNoTsubasa** [comment]
But why can't I just edit the strictnesses without applying one thing to the other?

And yeah, filterblade.

**Comment by NeverSinkDev** [comment]
Because you're NOT editing the strictness, you're editing a loaded filter file and FilterBlade only ever has 1 file loaded. 

If you switch to a different strictness you're transferring your changes. If you want a different set of changes, save that one on the save/load screen, download the filter, then reset and select a different strictness.

**Comment by AkumaNoTsubasa** [comment]
Urgz... hm okay. thanks!

**Comment by NeverSinkDev** [comment]
I just edited my comment, read it again, I think you can get what you want, by using the save load screen.
