### ISSUE TITLE
Eternal Burgonet "T1" and Royal Burgonet "T2" are Mis-Tiered, They are Reversed

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#138]
Royal Burgonet: 377 armour, currently listed as T2
Eternal Burgonet: 373 armour, currently listed as T1

377 > 373

This issue crops up at the very least in _Endgame - General (lvl 65+) - High level crafting - Normal Bases (non-rare)_, and _Normal Bases (rare)_

![image](https://user-images.githubusercontent.com/14173022/72179457-c668ef00-3399-11ea-9e1b-21f49a6e1c22.png)

**Comment by NeverSinkDev** [comment]
But.. more strength requirements for a near trivial amount of armour: 4.

That being said, I see your point and will consider this for the next update
