### ISSUE TITLE
Line 4381: Unable to parse parameter for BaseType rule: No base types found matching "Master Cartographer's Sextant"

### ISSUE THREAD

**Issue by Dattdk** [NeverSinkDev/NeverSink-Filter#139]
Error is keeping the filter from working at any level.

**Comment by NeverSinkDev** [comment]
You're using an outdated pre-metamorph version. Get the latest one.

**Comment by Dattdk** [comment]
Just deleted my Neversink folder, redownloaded 7.6 and installed. Still receive the same error when loading any filter level. Filter not working.

**Comment by NeverSinkDev** [comment]
One of the changes in 7.5 is removing this line. So you're not using 7.6.
Options:

1) you got the folder wrong
2) some security tool is blocking file modification
3) you downloaded the wrong version

Check everything again. It's usually the first one

**Comment by G9000** [comment]
<img width="1688" alt="Screenshot 2023-04-27 at 5 39 57 PM" src="https://user-images.githubusercontent.com/11317652/234824134-811c9559-86b6-49f8-8f65-7fe1f9fcaf62.png">

I'm using macos, is there anything i need to do?? I need the damn filter :'<

**Comment by G9000** [comment]
> <img alt="Screenshot 2023-04-27 at 5 39 57 PM" width="1688" src="https://user-images.githubusercontent.com/11317652/234824134-811c9559-86b6-49f8-8f65-7fe1f9fcaf62.png">
> 
> I'm using macos, is there anything i need to do?? I need the damn filter :'<

Never mind, not sure what happen but after redownload many times, it finally appear on the list :v .
