### ISSUE TITLE
Talismans Don't Get Hidden Even if you Disable Them

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#140]
They seem to be getting picked up by some other part of the filter. Steps to reproduce:

New filter, Very Strict, Customize, League-specific, Other Leagues, Talismans, Disable. Drop a Talisman on the ground. Still shows up.

Maybe just add a Hide button.

**Comment by KlSKE** [comment]
Hey there, your STR is good and I can reproduce it, but this is not an issue, if you don't want to see any talisman at all, even unique talismans, just change the **rarity** to **any**.

![image](https://user-images.githubusercontent.com/13884680/74899892-e0282980-537c-11ea-86e0-eb01735cdea8.png)

**Comment by dsnvwlmnt** [comment]
I want to see Unique Talismans, and hide Rare Talismans.

**Comment by NeverSinkDev** [comment]
I've added the hide button and the entry is now hidden instead of disabled on higher strictnesses. The default rarity setting won't hide unique talismans.

Closed.
