### ISSUE TITLE
Highlighting socket groups "W" does not work

### ISSUE THREAD

**Issue by ColdFaith** [NeverSinkDev/NeverSink-Filter#141]
Hi, 

i am trying to show items that have at least 1 white socket. 
I made the following settings in filterblade:
![White socket Filterblade setting](https://user-images.githubusercontent.com/24418813/74055563-7dc84400-49e0-11ea-83f5-bfc491464aac.PNG)

It results in the following text in the filter file:
Show 
SocketGroup "W"
SetBorderColor 0 255 0 255
SetFontSize 38
Class "Claws" "Daggers" "One Hand Axes" "One Hand Maces" "One Hand Swords" "Rune Daggers" "Sceptres" "Thrusting One Hand Swords" "Wands" "Shields"
SetTextColor 0 0 0 255
SetBackgroundColor 255 128 0 255

The problem is, the items are hidden (i am holding down the "Alt"-key in the picture). 
![image](https://user-images.githubusercontent.com/24418813/74056095-96852980-49e1-11ea-8e75-811230c144bb.png)

However, if i manually move the text to the very beginning of the filter file the items are shown. 
![image](https://user-images.githubusercontent.com/24418813/74056153-bcaac980-49e1-11ea-8296-534b49d84be6.png)

Am I doing something wrong or is there some bug or issue with the order?

Best regards, 
Tim.

**Comment by Tobnac** [comment]
Thats because the rule youre using is in the leveling section of the filter, as colors only really matter there.
You should be able to use the global custom rules at the bottom and add SocketGroup filtering there to fix this.

**Comment by ColdFaith** [comment]
You are absolutly right! Now it works. 

Thank you very much :)!
