### ISSUE TITLE
Ancient Greaves and Goliath Greaves swapped.

### ISSUE THREAD

**Issue by tehyulekim** [NeverSinkDev/NeverSink-Filter#142]
https://pathofexile.gamepedia.com/Boots#Armour_Boots_.28Strength.29

Ancient Greaves [ Shown in very strict ]
Goliath Greaves [ Hidden in very strict ]
Vaal Greaves
Titan Greaves

Goliath Greaves is higher level base than Ancient Greaves, but very strict filter hides Goliath and shows Ancient. 
Fix should hide ancient greaves and show goliath greaves.

**Comment by tehyulekim** [comment]
Similar issue
https://pathofexile.gamepedia.com/Gloves#Evasion_Gloves_.28Dexterity.29
On Strict,
Shagreen Gloves are shown but
Stealth Gloves are hidden, but it's better than shagreen

**Comment by NeverSinkDev** [comment]
Will be fixed for 3.10, thanks
