### ISSUE TITLE
SetBorderColor is written twice 

### ISSUE THREAD

**Issue by He3F** [NeverSinkDev/NeverSink-Filter#144]
I have not looked throw all the styles and strickness, but for [velvet regular](https://github.com/NeverSinkDev/NeverSink-Filter/blob/d0f70823beee191c627d129a76096676cfa533ff/(STYLE)%20VELVET/NeverSink's%20filter%20-%201-REGULAR%20(Velvet)%20.filter) SetBorderColor is set twice for some sections. 

see line [5435](https://github.com/NeverSinkDev/NeverSink-Filter/blob/d0f70823beee191c627d129a76096676cfa533ff/(STYLE)%20VELVET/NeverSink's%20filter%20-%201-REGULAR%20(Velvet)%20.filter#L5435) and [5436](https://github.com/NeverSinkDev/NeverSink-Filter/blob/d0f70823beee191c627d129a76096676cfa533ff/(STYLE)%20VELVET/NeverSink's%20filter%20-%201-REGULAR%20(Velvet)%20.filter#L5436) 

its properly nothing, but i wanted to point it out

**Comment by NeverSinkDev** [comment]
Yeah, it's an error in the style file definition. It should not be causing any harm. I intend to rework the entire style system in one of the next updates, this bug won't happen then.

Thanks you.
