### ISSUE TITLE
Suggestion for a Revert Button to "Undo" Reset Button

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#145]
Currently if you click Reset anywhere in filter, it resets that section to whatever the default is. The problem is there's no way to go back to what you had.

Often I'd like to know what the default is, to see what exactly I had changed from the default. The only way I can do this currently is to open a private tab, see what the defaults of a blank filter are, and alt+tab a bunch to see what's different vs my filter settings.

If there were simply a Revert button, I could go back and forth with that and Reset to see changes. Similar to Undo/Redo functionality, but I'm not really suggesting Undo/Redo since that's presumably a lot more work.

**Comment by NeverSinkDev** [comment]
That's one of those features that is nice to have, but likely won't make it. We'd likely have to rework a major part of the current architecture to implement it.

**Comment by dsnvwlmnt** [comment]
Yeah I thought that might be the case, thanks.
