### ISSUE TITLE
unable to parse parameter...

### ISSUE THREAD

**Issue by viane** [NeverSinkDev/NeverSink-Filter#146]
![Capture](https://user-images.githubusercontent.com/4284629/76866726-eb1a9080-683a-11ea-9c96-fa800bc4030a.PNG)

Hi, this is the newest version of the filter that I downloaded with all setting to default, running on 3.10 just updated today,

Is there a way to debug this issue to find out what type of the error is?  syntax, unicode  etc...?

Thanks!

**Comment by NeverSinkDev** [comment]
That's a POE-gameclient related issue. The items have the correct names. Confirm that your installation is correct.
