### ISSUE TITLE
Class Currency above top currency

### ISSUE THREAD

**Issue by Magiosnik** [NeverSinkDev/NeverSink-Filter#147]
Created a filter through the site, using veryStrict preset and shaper sounds. 

Noticed Exalted orbs were making Blessed Orb sounds and checked the filter. The regular Currency part is above the top tier currency part, so it catches that instead of the proper paragraph. 

Also Exalted Orb was missing from Show # $tier->t11 $type->currency
Checked on the site and it is showing there, including making the proper sound when tested through the simulation.

**Comment by NeverSinkDev** [comment]
We had some very rare bugs with some savestates issues and are working on them. The majority of them should be fixed now.
