### ISSUE TITLE
Path on disk for filter file

### ISSUE THREAD

**Issue by Unterstrichmoepunterstrich** [NeverSinkDev/NeverSink-Filter#149]
Hello,

I'm playing PoE with Steam on Debian Buster. 
If you want to add the filter put the files at 

> ~/.local/share/Steam/steamapps/compatdata/238960/pfx/drive_c/users/steamuser/My Documents/My Games/Path of Exile

and you can choose your loot filter. Maybe you can put the path into your FAQ.

**Comment by kian** [comment]
I can submit a PR for this if you tell me a way to identify the path?  Maybe there is an environment variable?

This looks specific to your setup.

**Comment by kian** [comment]
Not sure the best way to state this, but I submitted a PR for a fellow Debian user.  

https://github.com/NeverSinkDev/NeverSink-Filter/pull/157

**Comment by MindlessRuff** [comment]
> Hello,
> 
> I'm playing PoE with Steam on Debian Buster.
> If you want to add the filter put the files at
> 
> > ~/.local/share/Steam/steamapps/compatdata/238960/pfx/drive_c/users/steamuser/My Documents/My Games/Path of Exile
> 
> and you can choose your loot filter. Maybe you can put the path into your FAQ.

Just wanted to add, the path seems to be the same on Arch Linux.
