### ISSUE TITLE
Add T3 for Rare Rings/Amulets

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#150]
2 tiers for rings and amulets is a bit constraining (belts is fine since Stygian is basically T0). At the very high end Amber/Jade/Lapis Amulets and Ruby/Sapphire/Topaz Rings are suboptimal, but they are superior to the junk tier.

I'd like to do this but I can't:

T1: Agate Amulet, Citrine Amulet, Turquoise Amulet, Onyx Amulet
T2: Amber Amulet, Jade Amulet, Lapis Amulet
T3: Coral Amulet, Paua Amulet

T1: Coral Ring, Diamond Ring, Two-Stone Ring
T2: Ruby Ring, Sapphire Ring, Topaz Ring, Prismatic Ring
T3: Amethyst Ring, Gold Ring, Iron Ring, Moonstone Ring, Paua Ring, Unset Ring

**Comment by NeverSinkDev** [comment]
I'll consider it. Alternatively we'll add a button to add new tiers to rings/amulets

**Comment by NeverSinkDev** [comment]
The problem I see is the strictness system and highlight differences. I don't want to introduce additional highlight differences and I don't see any rings/amulets highlighted on uber strict, so it would be a filterblade only change. I dislike there.

**Comment by dsnvwlmnt** [comment]
Adding a button for Add Nevv tier vvould vvork for me.

**Comment by NeverSinkDev** [comment]
What happened to your "v" button?

**Comment by dsnvwlmnt** [comment]
My "w" key doesn't work on this computer. Sometimes I paste it from clipboard but sometimes I'm lazy. :)
