### ISSUE TITLE
All Essences being highlighted in v. 7.8.3

### ISSUE THREAD

**Issue by bashupoe** [NeverSinkDev/NeverSink-Filter#151]
Updated my filter to the newest version on filterblade today and all essences are being highlighted. Might be linked to the new "Essences while leveling" rule. I opted to disable this rule, but no change. 

![image](https://user-images.githubusercontent.com/47688893/79076203-99114180-7cf8-11ea-893d-0002d025dfad.png)

**Comment by NeverSinkDev** [comment]
Can't reproduce this. Do you have a save?

**Comment by bashupoe** [comment]
I've learned a bit more about the problem...
I use a filter version with a custom sound set for currency drops based off the shaper sound preset on the uber strict neversink HC economy settings. 
When I save and reload the filter, the second to last "New Currency Tier" seems to become corrupted. There's no items in it and it's drop style is applied to essences, legion and breach splinters and some other things.
Here's the save: http://filterblade.xyz/?profile=bashu&saveState=200412_Bashu%20&platform=pc

**Comment by NeverSinkDev** [comment]
This should not happen anymore. Closed.
