### ISSUE TITLE
Filter unable to locate sound filepath

### ISSUE THREAD

**Issue by XCaramellX** [NeverSinkDev/NeverSink-Filter#152]
So the filter is unable to load a sound file path. I even put all the sounds where the filter is supposed to be.
![image](https://user-images.githubusercontent.com/29244116/79084179-5fdccf80-7d00-11ea-95c3-9ccf44a998c2.png)
![image](https://user-images.githubusercontent.com/29244116/79084189-6e2aeb80-7d00-11ea-9485-67d0777312bd.png)

**Comment by NeverSinkDev** [comment]
place them a folder higher.
