### ISSUE TITLE
Hide stackable currency

### ISSUE THREAD

**Issue by abdukulov-talgat** [NeverSinkDev/NeverSink-Filter#153]
Not hiding "STACKS - COMMON SPLINTERS" if u remove / disable that option

**Comment by NeverSinkDev** [comment]
I just checked the section works fine.
Create a new item with more details.

**Comment by abdukulov-talgat** [comment]
Found problem, problem was in  poe. He don't update state immediately when
I sync filter state and refresh filter in game. Some times need to wait
5-10 min.

вт, 14 апр. 2020 г. в 12:18, NeverSink <notifications@github.com>:
