### ISSUE TITLE
Veiled Mods Section - Add Rule Bugged?

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#154]
If you try to Add Rule in the Veiled Mods section, AFAICT no matter what you do, when you try to Show the rule, it pops up the error below. (red outline emphasis added)

![image](https://user-images.githubusercontent.com/14173022/79171043-e4cdf480-7da5-11ea-80f8-686f8f843434.png)

**Comment by NeverSinkDev** [comment]
I gotta agree it's a bit counterintuitive. You need to add "Veiled" or "of the Veil" or anything else into the mods first. We'll improve that.
