### ISSUE TITLE
[Feature Request] Zero filter

### ISSUE THREAD

**Issue by 0ldi** [NeverSinkDev/NeverSink-Filter#155]
For leech exp in party, group leaders enforce to not loot anything on zone, so i try to make comfortable filter and cut everything...
It turned out quite normal, except for sections like this (this is not much, and rarely drop): 
![image](https://user-images.githubusercontent.com/16578229/79173342-e3311a80-7dff-11ea-855d-0f10886d9e66.png)
But the main problem is that I now hear the sound of a drop that does not appear, and I don’t know what and how to cut it.
I tried to mute all remaining unhidden sections:
![image](https://user-images.githubusercontent.com/16578229/79173641-e2e54f00-7e00-11ea-9780-54a3dcfd1aae.png)
I tried to mute here:
![image](https://user-images.githubusercontent.com/16578229/79173723-1aec9200-7e01-11ea-91c4-0b627312f75a.png)
But it doesn’t help, that anyway it drop with sound (without display), about once per second (6players on the Tower map with full shit)

Could you make a separate filter for such (very popular) purposes?
(Z button is not option)

**Comment by NeverSinkDev** [comment]
Advanced -> Quick Functions -> Remove All Sounds
Advanced -> Quick FUnctsion -> DisableDropsound
