### ISSUE TITLE
Cannot Easily Differentiate _Quality_ Vaal Gems from Quality Gems

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#156]
The GCP recipe overrides the (levelling) Gems section, and the Miscellaneous.SkillGems section doesn't have a dedicated Vaal section. I could use Top Vaal Gems but i'd rather not since that's for levelled Vaal gems.

The best I could figure was to Add a new Skill Gem Tier to Skill Gem Tiers, manually adding every Vaal gem one by one. A bit tedious but it seems to be working.

I thought maybe you could add one more sub-section like "Top Vaal Quality Gems", as I can't be the only person who cares about medium-low quality Vaal gems later on in the game, but don't care about low-gcp quality gems at that point. Would rather quality vaal gems not forcefully get lumped in with regular gems and/or overriden by the GCP section.

**Comment by Tobnac** [comment]
Sorry for the inconvenience, but you could always just write "Vaal" into the Gem list and it would catch all Vaal gems.
That being said, the 8.0 filter, which is currently on https://beta.filterblade.xyz/ and on the live site this Friday for the 3.14 launch, has a dedicated Vaal gem rule with Quality slider. Leveling rules also have priority over the GDC rules.

Also, I'm not sure if this was already the case when you opened the issue, but the current live version also has a rule in Gem Tiers -> Tier 2 for Vaal gems only with a Quality slider below.
