### ISSUE TITLE
Basetype can cause error

### ISSUE THREAD

**Issue by btsrkex** [NeverSinkDev/NeverSink-Filter#159]
There are rare cases that lines start with "Basetype ==" or "Basetype = " cause the filter cannot be recognized by the client, while "Basetype[space]" never has such a problem. I see neversink filter has a mix of all those presentations while they are working exactly the same. 
Can we get all "Basetype ==" and "Basetype = " replaced by "Basetype " so that I don't need to manually replace them when I meet errors?

**Comment by NeverSinkDev** [comment]
They are not the same. "Basetype =" is the same as no "BaseType " -  a string contains search-

"BaseType ==" is an exact match operator, that solves several issues with divination cards, uniques etc.

I'm aware that there are rare problems with ==. I'm not yet sure how or when they happen, but a restart fixes those and currently I don't see enough reason not to use ==.
