### ISSUE TITLE
Make a shortcut to %userprofile%/Documents/My Games/Path of Exile

### ISSUE THREAD

**Issue by Opzon** [NeverSinkDev/NeverSink-Filter#16]
Hey, this isn't an issue but I think it would be easier if you added a folder shortcut to the path %userprofile%/Documents/My Games/Path of Exile
how you can do this is make a folder shortcut from somewhere on your PC to your desktop. Right click it and go to properties and then edit the destination to "%userprofile%/Documents/My Games/Path of Exile" **including the quotes.** So it will be a simple drag and drop for most people. Hope to see this in the next update <3 thanks for the amazing filter! If you need pictures or the instructions are unclear let me know.

**Comment by IanWilson1871** [comment]
There is a button ingame underneath the list of filters that you can press to open the location to place filter files if you can't find it yourself.

**Comment by Opzon** [comment]
@IanWilson1871 ya but it'd help players that don't know too much. Makes for a simple drag and drop. Not like it'd hurt anyone.

**Comment by NeverSinkDev** [comment]
It's a nice idea, I might integrate it in the next update.

Thank you.
