### ISSUE TITLE
New Error Caused by Your Update to Miscellaneous Additional Show/Hide Rule

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#160]
I noticed Filterblade added in this league _Jewel, Flask, Map_ to the **Miscellaneous -> Add additional Show/Hide rules -> Add Class-Based Rules**. So I selected them all. But that causes the following error: 

**Line 304: Unable to parse parameter for Class rule: No item classes matching "Flask"**

The same error occurs for "Map" if you remove Flasks. Jewel work fine though.

If you want to replicate, here's the filter section before and after that line, and an image of the Filterblade settings at the bottom.

#===============================================================================================================
# [[0200]] 6 LINKS
#===============================================================================================================

# FilterBlade: Conditional Entry
Show 
SetBorderColor 255 102 0 255
SetFontSize 45
ItemLevel >= 40
Rarity = Unique
SetTextColor 255 102 0 255
ItemLevel <= 43
SetBackgroundColor 0 0 255 255
PlayAlertSoundPositional ShGeneral 300
MinimapIcon 0 Pink Star
PlayEffect Pink
Class == "Bows" "Claws" "Daggers" "One Hand Axes" "One Hand Maces" "One Hand Swords" "Rune Daggers" "Sceptres" "Staves" "Thrusting One Hand Swords" "Two Hand Axes" "Two Hand Maces" "Two Hand Swords" "Wands" "Warstaves" "Body Armours" "Boots" "Gloves" "Helmets" "Shields" "Amulets" "Belts" "Quivers" "Rings" "Jewel" "Flask" "Map"

![image](https://user-images.githubusercontent.com/14173022/85213671-32229100-b316-11ea-97a9-2a2c65cffd39.png)

**Comment by Tobnac** [comment]
Thanks for letting us know! Will be fixed with the next update!
