### ISSUE TITLE
Highlighted Items Not Showing Initially

### ISSUE THREAD

**Issue by SmoofBrane** [NeverSinkDev/NeverSink-Filter#161]
Hello, I am using the custom sounds 7.9.1 semi-strict filter from github and my items aren't highlighted on drop.
When a valuable item drops, such as a chaos orb for example, the correct sound plays but I don't see the item itself.
Since the 7.9.0 update to the filter I have had to manually press the highlight button to show items, but that shows me everything.
Before then, valuable items would always show up, and 'normal' items wouldn't.
I am not sure if this is the intended functionality or if this is a bug, but in any case, I much preferred the previous version.

If it is not quite clear what I mean, I want highlighted items to show up when dropped, but hide after pressing and releasing the highlight key. This way I would immediately see important items, but they wouldn't persist on screen. The 'always highlight' function clutters the screen, but turning this off doesn't even show the item name when it initially drops, which is the issue that arose in the 7.9.0 update.

Any help would be greatly appreciated.

**Comment by NeverSinkDev** [comment]
Sadly I don't think I can do much about that. There's no filter commands that influence that.

GGG might've changed the configuration on how disabled always highlight works.

Best thing I can recommend is giving everything you care about beams or minimap icons.
