### ISSUE TITLE
Filterblade Where are "Remaining Gems With Quality" Caught?

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#162]
I must be missing something as I can't find a section for remaining generic gems _with quality_.

That can't be added here either as the Add Rule doesn't allow you to select by Class. You'd have to type out literally every gem name into BaseType.

You can't add them in _Additional Class-Based Rules_ at the end of the filter either, as Gem/Gems isn't listed as a Class.

![image](https://user-images.githubusercontent.com/14173022/85421339-2bb83300-b529-11ea-89ba-9c58e3cdd11a.png)

**Comment by Tobnac** [comment]
Its at the very top of the customizer:
General -> Vendor Recipes -> Gemcutter's Prism -> Low quality gems.
