### ISSUE TITLE
Cannot disable leveling magic jewelry ilvl <= 24

### ISSUE THREAD

**Issue by coffeecrank** [NeverSinkDev/NeverSink-Filter#163]
Cannot seem to disable the rule for leveling magic jewelry of ilvl <= 24. Here's the screenshot:
https://imgur.com/a/ulknjPc

Disabling/hiding it doesn't work and reverts back to the "enabled" state once the loot filter is reloaded.

**Comment by NeverSinkDev** [comment]
Will be fixed in the next update, thanks
