### ISSUE TITLE
FilterBlade Where are the Seeds options?

### ISSUE THREAD

**Issue by Firedrops** [NeverSinkDev/NeverSink-Filter#164]
Can't seem to find the customization sections for Harvest's Seeds.

**Comment by Tobnac** [comment]
They're right here, at the top of the Customizer where the current league content always is: General -> Current League: Harvest -> Seeds.

![image](https://user-images.githubusercontent.com/20803858/85844663-60cfba00-b7a3-11ea-8555-1dcf09da55c6.png)

**Comment by Firedrops** [comment]
Thanks for the quick reply, I was browsing all the way at the bottom with the other Leagues.

**Comment by NeverSinkDev** [comment]
The new league is always up there

Am Fr., 26. Juni 2020 um 11:56 Uhr schrieb Firedrops <
notifications@github.com>:
