### ISSUE TITLE
Items displayed in the Sacred Grove that are usually hidden.

### ISSUE THREAD

**Issue by scottord** [NeverSinkDev/NeverSink-Filter#166]
Hello,

I've noticed that there's an awful lot of stuff that drops in the Grove and just noticed that my filter, which is "strict-ish" was showing level ~63 drops from lower level seeds in a level 81 area. Loot was correctly filtered in the map zone.

Screenshot is [here](https://imgur.com/a/d2UgM5Z).

Please let me know if there's anything I can do to verify and/or assist!

Thanks.

**Comment by NeverSinkDev** [comment]
That was probably some low level seeds/plants that you still stacked up.

In any case, closed since harvest is going away.
