### ISSUE TITLE
Partial names in exact-match : really old filter 

### ISSUE THREAD

**Issue by RealLacuni** [NeverSinkDev/NeverSink-Filter#167]
Have a pretty customized filter ive used for more than a year every league, and the past two leagues have introduced an error where certain specific div cards are missnamed, causing the filter to be unusable until they are removed. After removing the wrong names, if the filter is then reloaded they return so theres no way to effectively remove them for good. 

Is there a way to permanently stop them from being reintroduced into the filter? 

![image](https://user-images.githubusercontent.com/71047915/93390163-43a70680-f83b-11ea-9b83-115f14145995.png)

**Comment by NeverSinkDev** [comment]
Sadly we have some troubles with migrating very old saves into new versions. We tried to cover *most* of the cases, but there's some edge cases, that are 0.001% of all saves and would take dozens of hours to create decent fixes.

I recommend completely resetting the divination card section. That will fix it and make the save file behave properly.
