### ISSUE TITLE
Unnecessary block in [4606] Heist Currency

### ISSUE THREAD

**Issue by EndlessCheng** [NeverSinkDev/NeverSink-Filter#168]
https://github.com/NeverSinkDev/NeverSink-Filter/blob/b2036f7257e402c30ff673812050926b2f576e25/NeverSink's%20filter%20-%201-REGULAR.filter#L6078-L6080

**Comment by NeverSinkDev** [comment]
Has been fixed a bunch of updates ago, thanks!
