### ISSUE TITLE
Cannot seem to edit Chancing section of Strict filter

### ISSUE THREAD

**Issue by SecretAgentSteve** [NeverSinkDev/NeverSink-Filter#171]
Tried a few things. Not editing it at all and reinstalling the filters seemed to do nothing, as no chancing items show up on the filter. It was working fine, default and edited on semi-strict, but the moment I swapped I no longer get anything from that section highlighted. Any input would be appreciated.

**Comment by NeverSinkDev** [comment]
Just tested it and it works fine for me ingame with these settings

![image](https://user-images.githubusercontent.com/2942999/97094894-986b4780-1659-11eb-863f-72bb03c7b0c5.png)
