### ISSUE TITLE
Large Clusters hidden on Uber Plus Strict

### ISSUE THREAD

**Issue by jcai1** [NeverSinkDev/NeverSink-Filter#172]
Uber Plus Strict hides all Large Clusters under i84, but certain bases are valuable even below i84. For example, currently, 8 passive minion damage is worth 80c, and 8 passive chaos damage is worth 10c.

The most comprehensive solution would be economy-based tiering of EnchantmentPassiveNode. In the meantime I think Large Cluster Jewels shouldn't be hidden by default even on Uber+ Strict.

**Comment by NeverSinkDev** [comment]
Fixed since last update, thanks
