### ISSUE TITLE
Improve Automatic Saving on Filterblade

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#173]
No proper Autosave in 2020 is fookin' killing me. Pleeeeeeease. Please save our progress as changes are made on filterblade.xyz. Closing the tab or browser should not completely eleminate **everything** you just did.

And/or saving changes shouldn't require so many clicks away from filter editing. If you want saving to remain manual, at least put a "Save to current selected filter" button visible at all times, like the Search/Color/Mark section. Currently super-tedious as you have to go away from what you are doing, and that's if you even think to do it:
1- click Save & Load
2- scroll down and click Save on your current filter
3- click Customize to go back

Edit: So I just noticed that some life-saving functionality related to what I want already exists in the form of "Load last auto-save", that you get when you return to the site. I'll just start using that I guess.

In the past I avoided using that because it seemed buggy, in that it wasn't matching what my saved filter would have. But perhaps I'd misunderstood how it works. It says "auto-save" but really it's just a temporary save of what you were doing, and isn't stored in your "save & load" list. Two forms of save that don't interact and aren't described to be unrelated.

**Comment by NeverSinkDev** [comment]
The auto-save feature works and is it indeed "just" a local save. That being said, I'm afraid cloud based auto-saving will not be a thing. Too many users, too little resources. 

We do want to make the save load approach a bit easier by merging save/download to allow 1 click exports and also add the button to the customizer. This is currently planned for next league, but I'll have to check up with @Tobnac on that topic again.

That being said, we'll probably have to add a "cooldown" and disable the hot-save during new league launches. 10k users spamming the database simultaneously fries our servers.

Closed.
