### ISSUE TITLE
Stacked GCP Missing on UberStrict in FilterBlade

### ISSUE THREAD

**Issue by tgavankar** [NeverSinkDev/NeverSink-Filter#174]
There's no entry for stacked GCPs on UberStrict in Filterblade (in the Fusing tier), while it exists in the unstacked section; this hides the drop. Heist can drop stacked GCPs (it hid a 10x stack drop which I happened to see by luckily pressing alt).

**Comment by NeverSinkDev** [comment]
Will be fixed in the next update, thanks
