### ISSUE TITLE
"Orb of Alteration" seems like in a wrong block

### ISSUE THREAD

**Issue by EndlessCheng** [NeverSinkDev/NeverSink-Filter#176]
It is in a same block with currency like "Orb of Alchemy", is this a mistake?

https://github.com/NeverSinkDev/NeverSink-Filter/blob/80a6ea255a8040551ce4b31d7800f901cd9e4797/NeverSink's%20filter%20-%201-REGULAR.filter#L6266

**Comment by Tobnac** [comment]
Thanks for the input, this is intentional tiering due to the increased demand of the item and the current economy.
