### ISSUE TITLE
Suggestion: Allow Dragging/Rearranging Order of Sections in Sub-Sections of "Add Additional Show/Hide Rules"

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#177]
Just had an extremely tedious situation that really shouldn't be difficult to code around.

I had 3 related Class-Based rules, let's call them A, B, C. I had them in that order. I realized I need to make them B, C, A because A was overriding B and C making them useless. Easy right? Just move A to the bottom. Except you can't. OK still not too bad cuz you can Remove A and re-add it to the bottom, right? **Wrong.** You can't Remove specific entries, only the **last entry**. So I had to delete C, B, A, then recreate them all in the order I wanted.

Ouch. I didn't even have that complicated of a setup to fix. I can imagine much worse. The more related entries you have, it gets exponentially harder to fix.

Worst case let us Remove entries other than the very last one...

**Comment by jpwalsh1** [comment]
Few people have mentioned this to me as well, the ability to change order/drag&drop or somehow easily shift things up and down would save us a lot of time when developing customized filters with the website UI.
