### ISSUE TITLE
I Vaaled My Filterblade Account i.e. Fatal Save State Errors (old title: Couldn't Save Freshly Loaded Filter to New Blank Entry)

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#178]
I have corrupted some of my filterblade saves and my account is in an invalid state. Logging off and starting over doesn't help.

How did we get here? Since there's no way to Copy filters in the Save list, I Loaded my "master" filter #4 from the list, and Saved it to a new entry #8 (after league launch). Or tried to. The first time you attempt that, it gives you a generic error, something like "nothing has been configured so there is nothing to save". If you try again, it doesn't give an error anymore, but now those 2 filters and your account are corrupted.

1- The main filter #4 and the copied filter #8 show the correct number of changes in the Save list, but after Loading them when I Customize, they are completely blank default filters with no changes.

2- Now the first time I click Load on a corrupted filter, nothing happens (well, it loads a blank filter quietly). The second click of Load of any of the corrupted filters pops up the blue "successfully loaded", but they remain blank in Customize.

Note that other filters I haven't touched in this scenario remain fine and editable. And loading the Autosave works and Saving  that works (but isn't exactly the version I want).

Along the way trying things and trying to save my master filter from oblivion, having it open in another tab, I tried to Save it on top of entry#8, which showed as blank since I'd Saved on another tab. It gave an error that you can't save over it, which is reasonable.

So I saved to entry#9, which was successful, but is a corrupted entry as well. Now when I go to my Saves list on a freshly loaded filterblade.xyz, I get the error:

![image](https://user-images.githubusercontent.com/14173022/104785722-12363d00-5740-11eb-804d-bd53fc3fdeed.png)

If I log out and hard refresh, and log in this is the error I get when trying to click on #4:
![image](https://user-images.githubusercontent.com/14173022/104816080-9f73a300-57cd-11eb-85e7-2594d71e2272.png)

**Comment by Tobnac** [comment]
Can you check again if this issue is resolved?
If not, can you please send your profile name (if the saveStates are public) or sharing link to the problematic saveState?

**Comment by dsnvwlmnt** [comment]
I've been checking daily, but it does appear to be working today! Thank you.
