### ISSUE TITLE
Filter does not hide whites on highlight

### ISSUE THREAD

**Issue by aleksejs-fomins** [NeverSinkDev/NeverSink-Filter#180]
Roughly for the last 3 leagues my filter shows all items when I hold the highlight key (ALT) as default. The filter still behaves as expected when I don't hold the highlight key. Namely, when I switch to a more strict filter, I see less expensive items disappear as expected. However, the highlight key behaves exactly the same for all loot filters. I have checked with my GF, and for her the highlight key does not show white items on stricter filters. Is this expected behaviour? Can this be fixed and how? I'm on Win7 and I'm not currently using any additional mods, although I had overwolf installed in the past.

**Comment by dsnvwlmnt** [comment]
Just as a sanity check here, you know you can't hide things from ALT right? Every single item will be visible no matter what.

If you could, people would double-hide everything so they don't crash in high Deliriums if they accidentally hit ALT.

**Comment by Tobnac** [comment]
> Just as a sanity check here, you know you can't hide things from ALT right? Every single item will be visible no matter what.
> 
> If you could, people would double-hide everything so they don't crash in high Deliriums if they accidentally hit ALT.

This exactly.
Can you give us an update on the topic?
I doubt this is a filter issue since the behavior your described is not possible to do with filters.

**Comment by aleksejs-fomins** [comment]
Sorry for delay, I forgot to answer. Indeed, the behaviour at my PC seems to be expected: I only see filtered items normally, and when I hit ALT I see everything. I still need to check my GF's PC. Because, as I said, for her the behaviour was fundamentally different, she did not show everything on ALT. I'll check and write back

**Comment by NeverSinkDev** [comment]
You can switch the item highlight/pickup key in the options.

Ultimately, this is not an issue with the filter itself.
