### ISSUE TITLE
Auto Sort creates errors

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [NeverSinkDev/NeverSink-Filter#181]
Example: https://www.filterblade.xyz/?profile=AkumaNoTsubasa&saveState=Anime%20Filter%20V%20Strict&platform=pc

![image](https://user-images.githubusercontent.com/627469/105578021-9cecec80-5d7d-11eb-8c1d-93bbc4b51c6b.png)

I am getting these errors. This started only after the update of the filter to 3.13 and has not happened before. New the newdate sadly did not fix this. Sadly I am unable to find out how to fix this temporarily myself, except I not using the auto filter by price.

**Comment by Tobnac** [comment]
Sorry for the late response, can you check if this issue still persists? You should be able to click the "x" on the items in the unique tierlist which will move them into the "Hide"-tier at the bottom of the tierlist. Clicking on the circle-arrow on the items there again will finally remove them. Right now I can not reproduce the issue so I presume it was an issue with either the data from Poe.ninja or our handling of it.

**Comment by NeverSinkDev** [comment]
Probably was only a temporary bug. Closed.
