### ISSUE TITLE
Suggestion: Add Level Dropdowns to Vendor Recipes Section

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#182]
Currently the vendor recipe section is just a blanket always on or off. That could be improved by simply adding an ItemLevel line to each (AreaLevel for the gems).

That way I can refine my filter to hiding Bauble recipe items starting from e.g. Level 78, GCP gems starting from Level 82, etc. Right now mid-league I have to manually turn these off and I can't tailor anything (without adding obtuse custom override sections).

.

Edit: Other sections have similar issues. Chancing doesn't let you choose when you stop caring (not relevant for HH but certainly for the other ones). And Endgame Rares - T3 and T4 Droplevel Settings is a blanket always on or off. Add dropdown for ItemLevel to let us choose when we don't care anymore.

I realize you can have different filters for different stages in the league. But who wants to manage multiple filters when you can have 1 that you just tailor to area levels? GGG has added more refinements like AreaLevel, but the filter hasn't really been refactored to fully take things like this into account.

**Comment by Tobnac** [comment]
Thanks for the input, this issue is resolved with the 8.0 filter update, currently available on http://beta.filterblade.xyz/ and on the live site for the 3.14 league this Friday.
(Beta currently only has it for Vendor Recipes. Rare items will receive it later - before league launch)
