### ISSUE TITLE
Highlights for Essence modded items (Haewark passives)

### ISSUE THREAD

**Issue by widardd** [NeverSinkDev/NeverSink-Filter#183]
Just discovered that your filter just treats tham as regular rares and skipped a few amazing items.
Could these get highlighted like enchanted items?

Thanks!

**Comment by Tobnac** [comment]
Thanks for the input, this issue is resolved with the 8.0 filter update, currently available on http://beta.filterblade.xyz/ and on the live site for the 3.14 league this Friday.
