### ISSUE TITLE
Priority issue with Additional Cluster Jewel Rules

### ISSUE THREAD

**Issue by aleab** [NeverSinkDev/NeverSink-Filter#184]
Additional Cluster Jewel rules are always added under `[1602] Medium Jewels` regardless of the actual base type selected, so rules for Large Cluster Jewels don't work.

For example, this is the filter I get after adding an Additional Cluster Jewel Rule for Minion Damage large cluster jewels.

```
#------------------------------------
#   [1602] Medium Jewels
#------------------------------------

# FilterBlade: Conditional Entry
Show 
SetBorderColor 220 0 185 239
SetFontSize 45
Class "Jewel"
AnyEnchantment True
BaseType "Large Cluster Jewel"
MinimapIcon 1 Orange Pentagon
PlayEffect Orange
SetBackgroundColor 56 20 94 255
PlayAlertSound 16 300
SetTextColor 206 164 52 255
EnchantmentPassiveNode "Minion Damage"
Rarity <= Rare
ItemLevel >= 75
EnchantmentPassiveNum = 8

Show # optimal size + level
	ItemLevel >= 84
	Rarity <= Rare
	EnchantmentPassiveNum <= 5
	BaseType "Medium Cluster Jewel"
[...]
```

**Comment by Tobnac** [comment]
Thanks for the input. This issue was resolved with a recent update - now the custom rules are at the very top of the section and overwrite all other cluster jewel rules.
