### ISSUE TITLE
"Endgame - General (lvl 65+), High level crafting" Should Be Corrupted=False

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#188]
It's a crafting section, but it includes corrupted items? Doesn't really make sense. Doubly so for the Normal/Magic subsections.

![image](https://user-images.githubusercontent.com/14173022/109457677-2bedc400-7a10-11eb-829f-4ead55903ac3.png)

**Comment by Tobnac** [comment]
Thanks for the input, this issue is resolved with the 8.0 filter update, currently available on http://beta.filterblade.xyz/ and on the live site for the 3.14 league this Friday.
