### ISSUE TITLE
Chromatic recipe in Leveling section has an area level gap

### ISSUE THREAD

**Issue by rkgibson2** [NeverSinkDev/NeverSink-Filter#192]
In the leveling section, the large and medium chromatics sections both have maximum area levels on the rules. This means that if you want to show these items in areas between area level 32 and 65 (or between 45 and 65 for medium chromatics), there's no good way to do this in the filter besides the Desired SocketGroups section.

Would it be possible to make this a configurable property or add other rules for these area levels?

**Comment by Tobnac** [comment]
Thanks for the input, this issue is resolved with the 8.0 filter update, currently available on http://beta.filterblade.xyz/ and on the live site for the 3.14 league this Friday.
