### ISSUE TITLE
Identified rares show with bad mods because of the base (suggestion)

### ISSUE THREAD

**Issue by coffeecrank** [NeverSinkDev/NeverSink-Filter#193]
Currently, identified rares show with crappy mods IF you choose to show these bases. While you might wanna show unid'd bases, the id'd ones should be hidden if mods are bad.

Let's say I want to show Onyx amulets. While I want to see unid'd amulets for a chance of good stats, I do not wanna see crap stats if I already know they're crap.

Hope it makes sense, and thanks for your work, as always!

**Comment by NeverSinkDev** [comment]
It's a reasonable suggestion, however the ident-mod process is not perfect, so items might slip through the cracks.

That being said, I'll definitely add an optional section on filterblade for hiding these
