### ISSUE TITLE
Chaos Recipe: Custom Show/Hide decorations overwritten by Endgame rare decorations.

### ISSUE THREAD

**Issue by IAmAnAzgul** [NeverSinkDev/NeverSink-Filter#195]
When attempting to use the custom borders for the chaos recipe, size is the only modification that has an effect on the items in the custom Show/Hide rules. The border, background, and text color are overwritten by the decorators for endgame rares. The exception to this rule is jewelry and belts which seem to be working correctly.

**Comment by Tobnac** [comment]
Could you please provide an example for this issue? I'm having trouble following the problem.
Also confused because all of the decorators and custom rules are basically identical.

**Comment by IAmAnAzgul** [comment]
![Screenshot 2021-04-18 091220](https://user-images.githubusercontent.com/82742967/115152829-af4a8f80-a027-11eb-950b-77e6cee1cc07.png)

**Comment by IAmAnAzgul** [comment]
![Example 1](https://user-images.githubusercontent.com/82742967/115152839-be314200-a027-11eb-8efb-697b0633bdf3.png)
An example of an ilvl 70 and 73 hel (within the rules but one is t3+ the other is t2
The t2 is correctly decorated and sized. the t3 is corectly sized and the text is the right color, but uses neither the decorator border OR the chaos recipe border.

**Comment by IAmAnAzgul** [comment]
![Screenshot 2021-04-18 092831](https://user-images.githubusercontent.com/82742967/115153066-d2c20a00-a028-11eb-935d-9c7cc656fad2.png)
A Pair of belts to demonstrate that the rule works correctly for them.

**Comment by IAmAnAzgul** [comment]
![Example 2](https://user-images.githubusercontent.com/82742967/115153083-ee2d1500-a028-11eb-9854-e7e0b3421ca0.png)
A pair of belts to show the rule works correctly for them.

**Comment by IAmAnAzgul** [comment]
if I add a backgroud color to the chaos recipe rule for anything but jewelry this happens.
![Screenshot 2021-04-18 093621](https://user-images.githubusercontent.com/82742967/115153183-8cb97600-a029-11eb-82a9-cdfc8a81819b.png)

**Comment by IAmAnAzgul** [comment]
This is what the simulator on the website shows for that Lordly Plate in the previous image.
![Screenshot 2021-04-18 094020](https://user-images.githubusercontent.com/82742967/115153309-1bc68e00-a02a-11eb-94a7-db0623f181c1.png)

**Comment by IAmAnAzgul** [comment]
Interesting addendum, the recipe colors work correctly for corrupted identified rares in the level range on my end.

**Comment by Tobnac** [comment]
I'm not 100% sure but I think this is an issue with the continue/decorator rules that we noticed recently. It's a bug on GGGs side and we already contacted them. I'd put this issue on hold until we hear back from them.

**Comment by IAmAnAzgul** [comment]
Issue has been fixed as of todays PoE patch.
