### ISSUE TITLE
T2 Rare overrides Custom Show/Hide Rules

### ISSUE THREAD

**Issue by Dav1dde** [NeverSinkDev/NeverSink-Filter#196]
T2 Rare overrides custom rules defined in Custom Show Hide Rules

![image](https://user-images.githubusercontent.com/255721/115136283-14e64e00-a01f-11eb-8e19-73c91ec7fd8f.png)

![image](https://user-images.githubusercontent.com/255721/115136332-61318e00-a01f-11eb-8edf-399ddd2f2eed.png)

![image](https://user-images.githubusercontent.com/255721/115136294-2af40e80-a01f-11eb-9039-9286bfc46765.png)

When I remove `Siege Axe` from the T2 Rares list, it correctly takes my custom rule.

**Comment by IAmAnAzgul** [comment]
Your custom rule affects t3 and lower items, Siege axe is t2, does changing your custom rule to ALL RARES make a difference?

**Comment by Dav1dde** [comment]
@IAmAnAzgul that was it, thanks!
