### ISSUE TITLE
Question about 8.0.0b 1-Regular

### ISSUE THREAD

**Issue by VetrinusTaleshire** [NeverSinkDev/NeverSink-Filter#197]
Double rarity on line 2830:
https://i.imgur.com/Ds34bee.png

	Rarity < Rare
	Rarity <= Rare

And dozens of lines:

	Rarity Normal
	Rarity <= Normal

What's the point?

**Comment by NeverSinkDev** [comment]
None. A bug caused by the inheritance feature in my domain language. I'll improve it over the coming weeks.
