### ISSUE TITLE
Option to always show identified items

### ISSUE THREAD

**Issue by m1ckswagger** [NeverSinkDev/NeverSink-Filter#198]
Hi, with Ultimatum rewards often being identified rare items I noticed that many of them are not shown by the lootfilter.

Is there any way to always show identified rare items?

Thank you!

**Comment by Tobnac** [comment]
The filter already has a section for identified mod filtering, but you can always use custom rules on FilterBlade to show identified items. There are ones available in both the rare item and  the global custom rule section at the bottom of the customizer.

**Comment by m1ckswagger** [comment]
Thank you for pointing out all options. I missed the one located in the rare item section. I thought I'd have to set up mods for all the individual filters in the "identified mod filtering" section.
