### ISSUE TITLE
Itemfilter doesn't show text for Loath Veil Mind Cage

### ISSUE THREAD

**Issue by Oran** [NeverSinkDev/NeverSink-Filter#199]
Loath Veil Mind Cage doens't show any text
I haven't tried it with other similar item

The filter used is `FilterBlade_2_Semi-Strict`

![Screenshot 2021-04-18 183954](https://user-images.githubusercontent.com/42975732/115154987-a8e30480-a075-11eb-8667-280b2c8b74ff.png)
![Screenshot 2021-04-18 184018](https://user-images.githubusercontent.com/42975732/115154991-ab455e80-a075-11eb-9f25-8d20a3bd42e5.png)

**Comment by Tobnac** [comment]
I presume this is that issue with decorator/continue rules, which is a bug on GGGs side. We already contacted them about it. The only workaround right now is to specify maximum opacity for the non-decorator rule that is currently transparent.

**Comment by NeverSinkDev** [comment]
This was fixed by GGG recently and should be working fine.
