### ISSUE TITLE
COMPILATION: Font problems - missing fonts, wrong letters, strange fonts: info and discussion here.

### ISSUE THREAD

**Issue by 1010101010101** [NeverSinkDev/NeverSink-Filter#2]
Is there a way to fix the text overlap?

[Example](http://i.imgur.com/OjsLJM6.jpg)

**Comment by NeverSinkGaming** [comment]
I reported this bug to GGG and they said:
"The font on the item filter is a known issue, this does not have anything to do with the particular filter that you are using."
So I think it'll be fixed sooner or later. It affects <5% players (judging by the number of PM's :p, though I might be wrong) and I suspect, it's somewhat related to the "new sound engine" or the preloading... Restarting the PC fixes it for most players, even if it's a temp. fix.

**Comment by 1010101010101** [comment]
Thanks for the explanation!

**Comment by stvndall** [comment]
I Lowered the text size to 41 and it was sorted on my side. it looks like it's something to do with the resolution of the game. Looks like there might be an attempt to wrap the text on multiple lines on space, however the game can't do multi line. I don't mind commiting this change if you want?

**Comment by NeverSinkGaming** [comment]
I don't think that's the solution. It happens on some systems and it's a very rare bug. I think for now, I'll just stop trying to create workarounds for this issue, considering how rare it is and that a game restart fixes it.

Thank you for your feedback/offer though.

**Comment by neomvll** [comment]
Last weekend I got this bug, after restart game, the bug was gone. I think this is a workaround at the moment.

**Comment by NeverSinkDev** [comment]
Yeah restarting the game is one way to fix it. Another way is to create a copy (physical file copy) of the filter and switch to the copy.

Also, I _suspect_ it has _something_ to do with certain applications running in the background. Also I've been recently been able to reproduce this bug intentionally and I think I start understanding why GGG could not do it. I'll post more, once I'll confirm my findings.

**Comment by Gumija** [comment]
I have encountered with the problem, and for me it seems like at certain height resolution ranges some labels are not visible. Messed around with changing height and width. And width does not seem to affect this. Took some screenshots as well: http://imgur.com/a/EUvlP

**Comment by sanjsanj** [comment]
I'm getting an error parsing line 2706 ingame for Maelström staff.  I think it's the letter "ö".

**Comment by shopofexile** [comment]
not so far

**Comment by Saiasanc** [comment]
@sanjsanj I don't get that error at all and I have the staff set to highlight for chancing purposes. Not sure what version you are using. But line 2706 for my version is a blank line under the "[2002] Hybrid flasks (normal)" section with no "Maelström staff" anywhere NEAR that line. So maybe time to update to a new version?

**Comment by axelsword** [comment]
I've noticed that claws don't display correctly to item level (filter 6.1 SOFT). It's important for chaos recipe.
![filter_colour](https://user-images.githubusercontent.com/37154132/42644150-c3984754-85f2-11e8-908b-7f5e3666b092.png)

**Comment by stvndall** [comment]
@axelsword is that because the claw Is higher than 75, and counts as regal recipe

**Comment by NeverSinkDev** [comment]
I haven't heard of similar issues since a while.

At the danger of having to reopen this - I'll close this topic for now.
