### ISSUE TITLE
Uniques

### ISSUE THREAD

**Issue by Gendono** [NeverSinkDev/NeverSink-Filter#20]
Loading the stric version works as intended, but the strict(blue) version doesn't play a sound when a unique drops, at least for me

referring to the line that just says rarity=unique and show

**Comment by NeverSinkDev** [comment]
I've just checked and the blue version seems perfectly fine. Please re-download it, maybe you've made some accidental edits?

**Comment by NeverSinkDev** [comment]
I'll assume that this is resolved.
