### ISSUE TITLE
The old style of your filters

### ISSUE THREAD

**Issue by leet0rz** [NeverSinkDev/NeverSink-Filter#201]
I think I am not alone in asking for the old style back, white map looks like life flasks, yellow maps looks like rare items etc. Div card just looked better before. Could we please get the old style back or the choice to use it? It was the best filter and the one I picked since 2014.

**Comment by KingKatura** [comment]
Agreed i wrote a question on it as well.

**Comment by NeverSinkDev** [comment]
I'll be improving certain aspects of the new default style, such as the maps and the T3 divinaiton card, but overall I'm pretty set upon the fact that the new style is better for clarity.
