### ISSUE TITLE
Scared flasks not showing

### ISSUE THREAD

**Issue by KingKatura** [NeverSinkDev/NeverSink-Filter#202]
With the normal filter sacred flasks are now hidden  and must use alt to find them.  Thanks for answering my other question before keep up the good work, if theirs anything me or someone can do to help let me know. **Sacred Flasks

**Comment by Tobnac** [comment]
I see the issue, will be fixed with the next filter update - in a few hours probably.

**Comment by NeverSinkDev** [comment]
fixed in the upcoming update. thanks
