### ISSUE TITLE
Rogue's Marker are not considered by my generated filter

### ISSUE THREAD

**Issue by music-p** [NeverSinkDev/NeverSink-Filter#205]
So the problem is that i generated a custom filter which should still show me the Rogue's Marker but in a non invasive way and when there are enough of them in a stack.
The filter seems fine, I already inspected it by hand. Still the game shows me all the Rogue's Marker that drop. In a weird Color (that was not defined as such) and it even plays the drop sound "3".

The only thing I noticed is that a lot of other heist items use this sound as well.

I attached a filter for you to test. In this file I even selected to hide the Rogue's Marker again.

[very-strict.filter.txt](https://github.com/NeverSinkDev/NeverSink-Filter/files/6339780/very-strict.filter.txt)

**Comment by KingKatura** [comment]
Idk if this post might help you or be simular but check it out since it was a simular issue it sounds like.  [https://github.com/NeverSinkDev/NeverSink-Filter/issues/185](url)

**Comment by music-p** [comment]
First of all, thanks for trying to help. I read that issue beforehand and i deemed it irrelevant for my issue since i am using the default "style" from Neversink (no vaal theme or anything else). However I have to agree there might be a similar issue at hand here; an override of the rule of some sort.
I want to stress again that not only is the sound and the appearance different from my settings. It also is not considering whether those Markers should be filtered out or not. They are **always** shown to me (with the filter that is attached).

**Comment by NeverSinkDev** [comment]
The way the filter works, is that every single currency is explicitely shown or hidden.

You have added a stacksize to the rogue markers. So every rogue marker that has lower stacksize than the one specified will be caught by a "safety section" that catches any explicitely unmatched item.

We'll try to improve filterblade for that case.
