### ISSUE TITLE
Shaper shield (1ex cost) don't show with lootfilter - 4verystr

### ISSUE THREAD

**Issue by M1dgard** [NeverSinkDev/NeverSink-Filter#206]
I'm using NeverSink-4verystr-softcore lootfilter and this item doesn't show. On 3strict it shows.\

![10](https://user-images.githubusercontent.com/82861611/115341407-c8dc0a80-a1d2-11eb-87a8-2fe8036f841d.png)
![20](https://user-images.githubusercontent.com/82861611/115341408-ca0d3780-a1d2-11eb-902b-5842bf64ab66.png)
![30](https://user-images.githubusercontent.com/82861611/115341410-caa5ce00-a1d2-11eb-8f81-c5bc8e9cc7da.png)
![40](https://user-images.githubusercontent.com/82861611/115341412-caa5ce00-a1d2-11eb-9648-9f686adb4233.png)
![50](https://user-images.githubusercontent.com/82861611/115341415-cb3e6480-a1d2-11eb-81fc-731a8e4fa0b8.png)

**Comment by NeverSinkDev** [comment]
all shaper/elder items are updated, based on the ingame economy. This should be adjusted in a couple of days.
