### ISSUE TITLE
FilterBlade: Rare tiering customizations are not loaded properly from save state

### ISSUE THREAD

**Issue by remd** [NeverSinkDev/NeverSink-Filter#229]
I have customized rare tiers for Two-Handed Maces, Warstaves, and (Armour) body armour base types in the "ENDGAME - RARE ITEMS (LVL 65+)" section.

The filter save state seems to save properly, but when loaded again my tiering customizations are not loaded.

Customizations I have made:
- Astral Plate T1
- Glorious Plate T2
- Coronal Maul, Terror Maul, Imperial Maul, Karui Maul, T1
- Meatgrinder, Piledriver, Colossus Mallet T2
- Judgement Staff, Maelström Staff, Ezomyte Staff T1
- Foul Staff T2

After reloading the save state you can see that my Warstaves customizations are gone and are returned to the filter's defaults:
![image](https://user-images.githubusercontent.com/1325809/139568102-2811eb45-82f6-440c-947c-26a979697db7.png)

I had previously saved and re-loaded this save state multiple times without experiencing this issue.

Shared save state:
https://www.filterblade.xyz/?profile=octeris&saveState=OOIUIBWYR827LM&platform=pc

**Comment by Tobnac** [comment]
A very recent update introduced a bug where BaseType-Matrix-changes were not saved correctly. I just deployed a hotfix for this. Can you verify that this resolves your issue as well? Sadly I presume your previous change can't be fully recovered from this since it was sitll saved incorrectly.

**Comment by remd** [comment]
@Tobnac Yep, it looks like it is fixed now. Thank you!
