### ISSUE TITLE
FilterBlade: Two Handed Weapon base type tooltips show old values

### ISSUE THREAD

**Issue by remd** [NeverSinkDev/NeverSink-Filter#230]
Multiple Two Handed Weapon base types in the rare tiering Basetype Matrix are not up to date. Their values changed in 3.11: https://www.pathofexile.com/forum/view-thread/2873739#twohandedweapons

All the base types affected in that patch are not up to date. Values from older patches are still listed in the base type tooltips. This makes re-tiering using the brush tool difficult without referencing a third-party data source such as PoEDB or the PoE Wiki.

**Comment by NeverSinkDev** [comment]
We're working on that one. One of the upcoming updates will overhaul the base data for all item types on filterblade
