### ISSUE TITLE
Custom sounds are in mono

### ISSUE THREAD

**Issue by martin951** [NeverSinkDev/NeverSink-Filter#232]
Hello!
I love creating my own sound for various reasons but unfortunately I am having this issue with FilterBlade, where:
1) in the website editor, changing volume does not seem to have any effect
2) in game (when dropping an item to test it), the sound seems to be mono

Comparison (Original audio file vs ingame recording):
Exalted Sound: [Google drive](https://drive.google.com/file/d/1Ytw_KLdcRDonSGW0ViYotgGfw2t5a3YG/view?usp=sharing)
Belt Sound: [Google drive](https://drive.google.com/file/d/19j7Muhmj95lJM2qqHCPFePvMv7UodJdk/view?usp=sharing)
INGAME: [Google drive](https://drive.google.com/file/d/1ICiX_5nRqLY70mwdnLzavufwWpgQNg2r/view?usp=sharing)

**Comment by NeverSinkDev** [comment]
The volume change should've been addressed already.

I can't reproduce the mono issue. Does it still cause problems for you? FilterBlade also doesn't modify any of the sounds on the site, so it might be a POE issue.
