### ISSUE TITLE
Can not update filter because of "Map"

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [NeverSinkDev/NeverSink-Filter#235]
[ERROR]PARTIAL NAMES IN EXACT-MATCH: "Map" Rule name: Unique Maps T1

This error blocks me from updating my filter.

**Comment by Psaakyrn** [comment]
As a temporary workaround, use the Stable version instead of the economy-updated version. Trying to find where and why this erraneous item is being added.

**Comment by Tobnac** [comment]
We're looking into this right now. The EcoData causes issues because of the Synth Unique Map changes in 3.17

**Comment by Tobnac** [comment]
Fixed. Reload FilterBlade with Ctrl + F5 if you still have any issues with this.

**Comment by AkumaNoTsubasa** [comment]
Awesome. Works!
Thanks a lot.
