### ISSUE TITLE
Loading a filter save state causes some hidden currencies to go 'untiered' and turn pink

### ISSUE THREAD

**Issue by remd** [NeverSinkDev/NeverSink-Filter#236]
https://www.filterblade.xyz/?profile=octeris&saveState=L8FE9O726V1ANH&platform=pc

Every time I load my filter save state to make changes some of my hidden currencies will go 'untiered' and turn pink. I can work around the issue by going to the affected currencies in the customizer and toggling their visibility on and off again.

**Comment by Tobnac** [comment]
We deployed a fix for this today. Can you verify that the issue is fixed?

**Comment by remd** [comment]
I have verified that the issue is fixed using my example save state. Thank you!
