### ISSUE TITLE
Cosmetic – messed numbers in 8.5.2 release

### ISSUE THREAD

**Issue by LordBlick** [NeverSinkDev/NeverSink-Filter#237]
Hello, I've written [some tool](https://github.com/LordBlick/LBfilterAgentPoE) to convert base release filter to my custom version. It's able to recognize and fix section/subsection numbering and for now it found following issues:

- Warning! Std Section with name „Hide All known Section” and Id:6002 decorated as Subsection, let's go back to Id:[[4900]].
- Warning! Std Section with name „Show All unknown Section” and Id:4804 decorated as Subsection, let's go back to Id:[[5000]].
- Warning! Subsection „Link Based” Id:[1234] has an unrelated ID to Section Id:[0900], fix–>[0901].
- Warning! Subsection „Expensive Atlas 86 Bases - matched by economy” Id:[1234] has an unrelated ID to Section Id:[1000], fix–>[1001].
- Warning! Subsection „Perfection-Based-Filtering” Id:[1000][1001] has now same ID as „Expensive Atlas 86 Bases - matched by economy”, fix–>[1002].
- Warning! Subsection „ILVL 86” Id:[1000][1002] has now same ID as „Perfection-Based-Filtering”, fix–>[1003].
- Warning! Subsection „ILVL 84” Id:[1000][1003] has now same ID as „ILVL 86”, fix–>[1004].
- Warning! Subsection „ILVL ANY” Id:[1000][1004] has now same ID as „ILVL 84”, fix–>[1005].
- Warning! Subsection „RGB Endgame” Id:[1000][1005] has now same ID as „ILVL ANY”, fix–>[1006].
- Warning! Subsection „Chisel Recipes” Id:[1000][1006] has now same ID as „RGB Endgame”, fix–>[1007].
- Warning! Subsection „Generic Decorators” Id:[4403] has an unrelated ID to Section Id:[3000], fix–>[3001].
- Warning! Subsection „Map progression” Id:[3000][3001] has now same ID as „Generic Decorators”, fix–>[3002].
- Warning! Subsection „Labyrinth items, Offerings” Id:[3000][3002] has now same ID as „Map progression”, fix–>[3003].
- Warning! Subsection „Supplies: High Stacking” Id:[4702] has an unrelated ID to Section Id:[3500], fix–>[3501].
- Warning! Subsection „Supplies: Low Stacking” Id:[3500][3501] has now same ID as „Supplies: High Stacking”, fix–>[3502].
- Warning! Subsection „Supplies: Portal Stacking” Id:[3500][3502] has now same ID as „Supplies: Low Stacking”, fix–>[3503].
- Warning! Subsection „Supplies: Wisdom Stacking” Id:[3500][3503] has now same ID as „Supplies: Portal Stacking”, fix–>[3504].
- Warning! Subsection „Stacked Currencies: 6x” Id:[3500][3504] has now same ID as „Supplies: Wisdom Stacking”, fix–>[3505].
- Warning! Subsection „Stacked Currencies: 3x” Id:[3500][3505] has now same ID as „Stacked Currencies: 6x”, fix–>[3506].
- Warning! Subsection „Stacked Currencies: Splinters” Id:[3500][3506] has now same ID as „Stacked Currencies: 3x”, fix–>[3507].
- Warning! Subsection „Heist Coins” Id:[3500][3507] has now same ID as „Stacked Currencies: Splinters”, fix–>[3508].
- Warning! Subsection „Incursion - Vials” Id:[5103] has an unrelated ID to Section Id:[3700], fix–>[3701].
- Warning! Subsection „Delirum Orbs” Id:[3700][3701] has now same ID as „Incursion - Vials”, fix–>[3702].
- Warning! Subsection „Delve - Resonators” Id:[3700][3702] has now same ID as „Delirum Orbs”, fix–>[3703].
- Warning! Subsection „Delve - Fossils” Id:[3700][3703] has now same ID as „Delve - Resonators”, fix–>[3704].
- Warning! Subsection „Blight - Oils” Id:[3700][3704] has now same ID as „Delve - Fossils”, fix–>[3705].
- Warning! Subsection „Expedition Currencies” Id:[3700][3705] has now same ID as „Blight - Oils”, fix–>[3706].
- Warning! Subsection „Essences” Id:[3700][3706] has now same ID as „Expedition Currencies”, fix–>[3707].
- Warning! Subsection „Incubators” Id:[3700][3707] has now same ID as „Essences”, fix–>[3708].
- Warning! Subsection „Others” Id:[3700][3708] has now same ID as „Incubators”, fix–>[3709].
- Warning! Subsection „Breach and Legion Splinters” Id:[5112] has an unrelated ID to Section Id:[3800], fix–>[3801].
- Warning! Subsection „Simulacrum Splinters” Id:[3800][3801] has now same ID as „Breach and Legion Splinters”, fix–>[3802].
- Warning! Subsection „Utility Flasks” Id:[6002] has an unrelated ID to Section Id:[4600], fix–>[4601].
- Warning! Subsection „Hybrid flasks” Id:[4600][4601] has now same ID as „Utility Flasks”, fix–>[4602].
- Warning! Subsection „Life flasks” Id:[4600][4602] has now same ID as „Hybrid flasks”, fix–>[4603].
- Warning! Subsection „Mana flasks” Id:[4600][4603] has now same ID as „Life flasks”, fix–>[4604].
- Warning! Subsection „Links and Sockets” Id:[6002] has an unrelated ID to Section Id:[4700], fix–>[4701].
- Warning! Subsection „Rares - Decorators” Id:[4700][4701] has now same ID as „Links and Sockets”, fix–>[4702].
- Warning! Subsection „Rares - Universal” Id:[4700][4702] has now same ID as „Rares - Decorators”, fix–>[4703].
- Warning! Subsection „Rares - Caster” Id:[4700][4703] has now same ID as „Rares - Universal”, fix–>[4704].
- Warning! Subsection „Rares - Archer” Id:[4700][4704] has now same ID as „Rares - Caster”, fix–>[4705].
- Warning! Subsection „Rares - Melee” Id:[4700][4705] has now same ID as „Rares - Archer”, fix–>[4706].
- Warning! Subsection „Purpose Picked Items” Id:[6002] has an unrelated ID to Section Id:[4800], fix–>[4801].
- Warning! Subsection „Normals” Id:[4800][4801] has now same ID as „Purpose Picked Items”, fix–>[4802].
- Warning! Subsection „Weapon Progression” Id:[4800][4802] has now same ID as „Normals”, fix–>[4803].
- Warning! Subsection „Remaining Magics” Id:[4800][4803] has now same ID as „Weapon Progression”, fix–>[4804].

Can I help you in some way to make those fixes not only on my disk? ;)

**Comment by NeverSinkDev** [comment]
Fixed in 8.X
