### ISSUE TITLE
Something's wrong with Sync to POE

### ISSUE THREAD

**Issue by mr-september** [NeverSinkDev/NeverSink-Filter#239]
![image](https://user-images.githubusercontent.com/45350177/159102506-4a007e3a-490a-4f76-a3aa-7a734fe02f5b.png)
Getting this error message after trying to sync to poe since yesterday, can't copy-paste it since it goes away upon interaction.

Is there something wrong with my filter specifically, or is this a broader issue?

UPDATE: Looks like there's something wrong with that filter specifically, because some other filters could still sync. This [buggy filter's share code](https://www.filterblade.xyz/?profile=Firedrops&saveState=OEOBPRBYJYCTBY&platform=pc). Is anyone able to tell what's wrong?

**Comment by Tobnac** [comment]
This is a "global" issue right now. PoE keeps refusing to update filters because they added a limit to how many updates one can do. We are in contact with them already to get this resolved.

**Comment by NeverSinkDev** [comment]
Should be fixed
