### ISSUE TITLE
div cards do not consider stack size

### ISSUE THREAD

**Issue by mrooney** [NeverSinkDev/NeverSink-Filter#240]
Hi there, thanks for the amazing filter!

I've been doing a lot of Ritual lately and noticed that on Uber-Strict, a bunch of valuable div card stacks are often hidden. One example of this was a stack of 3 "The Escape" which is classified as "TIER 4 - COMMON CARDS". This is 9 chaos (actually 12c for stack of 3). Meanwhile, a stack of 2 Emperor's Wealth are shown worth 2c total.

It would be awesome if there was a default separate tier for stacks (2+) of cards worth 2c+, that was adjustable by stack size and/or value.

**Comment by NeverSinkDev** [comment]
fixed in 8.8.0
