### ISSUE TITLE
Decorator for T10 map gain is in T11+ bracket

### ISSUE THREAD

**Issue by esfdk** [NeverSinkDev/NeverSink-Filter#241]
When editing filters on Filterblade, modifying the "Decorator: Tier 11+ gain" also modifies T10 maps dropping in area level 77 and below. 

Solution would be to move the T10 maps into the correct "bracket" or alternatively rename the decorator on filterblade.

P.S. Keep up the good work with both the filter and Filterblade!

**Comment by NeverSinkDev** [comment]
fixed in 8.8.0
