### ISSUE TITLE
wrong colors on portal scroll and scroll of wisdom

### ISSUE THREAD

**Issue by elemention** [NeverSinkDev/NeverSink-Filter#245]
is it a bug?
![3f8V4QE](https://user-images.githubusercontent.com/43981409/207234641-e90eb555-4346-4e23-97db-3cf335c53966.png)

**Comment by elemention** [comment]
upd: this behaviour only in acts, on maps colors is normal

**Comment by Tobnac** [comment]
This was fixed a few days later.
