### ISSUE TITLE
FilterBlade: Resetting appearance on disabled by default rule also re-disables rule

### ISSUE THREAD

**Issue by remd** [NeverSinkDev/NeverSink-Filter#247]
Noticed this on Crucible base types on Very Strict however it also occurs on other examples (e.g. "Remaining rares" in Campaign "Rare items" section, and "Identified endgame rares" in Endgame section).

![image](https://user-images.githubusercontent.com/1325809/230740156-60815b08-cd0a-465b-aaca-1aa055ae6fd2.png)

Pressing this button resets the appearance customizations AND re-disables the rule.

![image](https://user-images.githubusercontent.com/1325809/230740179-b2c41057-a727-4778-a7f8-7c172d4125f3.png)

Based on this tooltip I expected that only the appearance customizations I made would be reset:

![image](https://user-images.githubusercontent.com/1325809/230740027-64e928ca-e596-4dcd-b993-76628cddd363.png)

I'm guessing this is expected behavior but I'm not sure. 

Feel free to close if this is working as expected (and sorry for wasting your time)!

**Comment by Tobnac** [comment]
Yep, this is the intended behavior. That button resets all properties that can be changed with this UI, including sound, icon, and also the Show/Hide/Disable value.
