### ISSUE TITLE
Error on very strict

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [NeverSinkDev/NeverSink-Filter#248]
![image](https://user-images.githubusercontent.com/627469/230902831-d626feda-ff99-4ed8-a9da-f6a8ff6fbb35.png)
Getting this when downloading

**Comment by Adelbertt** [comment]
Having the same error on Strict 
![image](https://user-images.githubusercontent.com/34626275/230906020-e15d64a0-9408-4df9-89e3-65584c329aa1.png)

**Comment by Tobnac** [comment]
This error message was invalid and could be ignored. This was fixed a few days ago and we'll improve this in the future so it doesn't happen again.
