### ISSUE TITLE
Hidden tri-color Neversink v4.6

### ISSUE THREAD

**Issue by Buhuk** [NeverSinkDev/NeverSink-Filter#25]
Hi, im using your filter and i love too much.

I have found something that works poorly and I want to contribute to you by telling you.
I leave a picture for you to see the problem. -> [Image](http://imgur.com/a/Ra6DR)
I hope I have been helpful.

PS: Sry my poor english :p

**Comment by NeverSinkDev** [comment]
Yeah, it seems I've messed something up in the new leveling section.

I'll take a look at this during the upcoming economy update. Thanks.
