### ISSUE TITLE
Some incubators still showing up

### ISSUE THREAD

**Issue by zioarnold** [NeverSinkDev/NeverSink-Filter#250]
Greetings, 

I'm encoutering an issue with some incubators, I have created a filter which is currently syncing with my PoE account, so none offline files to play with. 

The issue is , here the list of incubators hidden:
![2023-04-14 15_18_13-](https://user-images.githubusercontent.com/11963029/232055186-458f0b93-cc7d-4dfc-b684-433a3cd8ed40.jpg)

Instead they are still showing up... why and how to fix as for instance it's showing up the Celestial Jeweller's Incubator.
![2023-04-14 15_13_32-Path of Exile](https://user-images.githubusercontent.com/11963029/232055098-0949d62f-5b2d-477c-9f96-b5ad15fa4036.jpg)

**Comment by zioarnold** [comment]
> Greetings,
> 
> I'm encoutering an issue with some incubators, I have created a filter which is currently syncing with my PoE account, so none offline files to play with.
> 
> The issue is , here the list of incubators hidden: ![2023-04-14 15_18_13-](https://user-images.githubusercontent.com/11963029/232055186-458f0b93-cc7d-4dfc-b684-433a3cd8ed40.jpg)
> 
> Instead they are still showing up... why and how to fix as for instance it's showing up the Celestial Jeweller's Incubator. ![2023-04-14 15_13_32-Path of Exile](https://user-images.githubusercontent.com/11963029/232055098-0949d62f-5b2d-477c-9f96-b5ad15fa4036.jpg)

Oops, nevermind, found a solution :-)

**Comment by Spacepuffin** [comment]
Wait, I'm having the same issue, what's the solution?

**Comment by Spacepuffin** [comment]
> Wait, I'm having the same issue, what's the solution?

Oh I found it, the hidden incubators were being shown since they were in the high level incubators category.

**Comment by zioarnold** [comment]
> Wait, I'm having the same issue, what's the solution?

Yep... :D
