### ISSUE TITLE
The Saviour not showing up with boss drops enabled

### ISSUE THREAD

**Issue by TerohsLab** [NeverSinkDev/NeverSink-Filter#251]
https://www.twitch.tv/videos/1803112774?t=9h5m44s

Its Uber Sirus and Ben said earlier that he turned boss drops on. About one min in, he even reloads the filter and drops the sword on the ground again .. for it to be hidden again.

I feel like that sword should show.

**Comment by NeverSinkDev** [comment]
Can't reproduce on any strictness:

![image](https://user-images.githubusercontent.com/2942999/234405139-f0992f01-b8f5-4933-a993-8bc69b265412.png)
![image](https://user-images.githubusercontent.com/2942999/234405226-4f6a27d1-af78-4f09-96eb-d0aa2690b545.png)

**Comment by NeverSinkDev** [comment]
Not reproducable/reply. Closed.
