### ISSUE TITLE
Divination Card prices are inaccurate

### ISSUE THREAD

**Issue by remd** [NeverSinkDev/NeverSink-Filter#253]
I noticed while poking around in my Divination Card section that the prices are inaccurate to a degree that makes auto-sorting by price relatively useless.

Just to hand-pick a few that I noticed:
The Betrayal
* FilterBlade: 4.6c
* poe.ninja: 3.8c
* poe.watch: 1.29c
* trade listings (up to a day ago) start at: 1-2c

The Puzzle:
* FilterBlade: 3.4c
* poe.ninja: 1c
* poe.watch: 1.91c
* trade listings (up to a day ago) start at: 1-2c

Thirst For Knowledge:
* FilterBlade: 5c
* poe.ninja: 2c
* poe.watch 1.65c
* trade listings (up to a day ago) start at: 1-3c

Thirst of Knowledge has never cost 5c according to poe.ninja or poe.watch this entire league, but FilterBlade is reporting the price at 5c. Why?

Thirst For Knowledge is particular interesting because FilterBlade reports in the Unique Item section that Gluttony is priced at 2.4c. The 5 cards required to get a Gluttony from div cards would cost 25c, but the item that results from that stack of cards is priced at 2.4c. It seems like FilterBlade could internally check its Divination Card prices against the Unique Item prices for logical consistency.

I haven't extensively looked through all the cards so I assume that in most cases FilterBlade is reporting a price higher than actual, but I wonder if it ever reports a price lower than actual, which would be even more concerning.

Thank you for your hard work on this amazing tool. I greatly appreciate it.

**Comment by NeverSinkDev** [comment]
Hey, thank you for the issue.

Filterblade takes it's economy data straight from poe.ninja. 

The filter generation actually does check the resulting reward, from most unique and currency related div cards.

We'll check if the script for poe.ninja is working correctly

**Comment by remd** [comment]
I just realized that my poe.ninja settings were set to Sanctum prices. 😳 I apologize for the incorrect and misleading data.

However, poe.watch was set to Crucible and my trade searches were against Crucible. I think FilterBlade is grabbing the economy data correctly from poe.ninja although I'm not sure why poe.ninja inflates the prices of the cards so much.

**Comment by remd** [comment]
Just a passing thought I had on this. Would it be possible to offer fetching prices via poe.watch as an alternative?

They have an API available at https://docs.poe.watch/ and from a cursory look have the same items listed that poe.ninja lists. One thing I see missing is item base types but I don't think FilterBlade offers item base type price import (please correct me if I'm wrong).

**Comment by jpwalsh1** [comment]
div prices are still out of wack, its flagging 1c cards for me when there is no reason why we need to be picking these up

**Comment by NeverSinkDev** [comment]
> div prices are still out of wack, its flagging 1c cards for me when there is no reason why we need to be picking these up

Please provide context.

Version, strictness, card, price, details etc

**Comment by jpwalsh1** [comment]
12/27

Very Strict

T14 Jungle Valley

Cards that still showed up on filter (all 1c at best)

Emperor's Luck
Lantador's
Fathomless

Very strict should not be showing me 1c cards anymore, or making any noise for them either.

**Comment by jpwalsh1** [comment]
![image](https://github.com/NeverSinkDev/NeverSink-Filter/assets/478326/726600a9-f1cb-4507-9e8b-2670ace967d2)

Ran a delly map, 10 cards in there the filter told me to pick up. 1 of them is valued more than 1c.

The Lion
The Penitent
The Gemcutter
The Wrath
The Calling
The Trial
Vinia's Token
Lost Worlds
The Wolf

The one worth more than 1c, was The Breach

**Comment by NeverSinkDev** [comment]
Very strict still shows a lot of random cards with potentially interesting outcomes and currency-like items.
Additionally use the latest version, many of the examples are actually hidden.

Emperor's Luck - highly random, fun, grants currency
Lantador's - hidden
Fathomless - hidden
Lion - random outcome with chance for jewel, ok
Penitent - Tricky one, large random pool, hidden on uber-strict as intended, but I see your point here.
Gemcutter - hidden
Wrath - Shown and it's ok
Calling - hidden
Trial - hidden
Vinia's - shown and ok
lost words - hidden
wolf - similar to penitent

Overall:
- Use latest version
- Upgrade to uber-strict

I'll be doing some readjustments to the expectations of the individual strictness experience, but your examples seem in the acceptable range.

**Comment by NeverSinkDev** [comment]
Old issue and has been mostly addressed.
