### ISSUE TITLE
Exotic Coinage not showing on very strict.

### ISSUE THREAD

**Issue by xecutable** [NeverSinkDev/NeverSink-Filter#256]
Currently Exotic Coinage does not show on Very Strict softcore. In the settings it shows as T2 in small and large stacks, but in-game I don't see them on the ground at all. There must be something that overrides it, because on filterblade I see it in 3 different places and the option Show is turned on..

**Comment by NeverSinkDev** [comment]
This has been fixed two hours ago, get the latest version
