### ISSUE TITLE
Possible problematic interaction from Gemcutter Recipe and +1 SKill Gem Recipe

### ISSUE THREAD

**Issue by mightyscrub** [NeverSinkDev/NeverSink-Filter#257]
On my filterset:

- All gems with quality >= 1 should be shown == all Gemcutter Recipes are activated
- the +1 Skill Gem Recipes are deactivated

By pressing ALT near a strongbox today i found a +7 Quality Cremation Gem.  After testing with usually disabled rules i realized, that the gem will be shown only if the +1 Skill Gem recipe is activated.  This is not the expected behavior. 

Best

**Comment by NeverSinkDev** [comment]
I've done some modifications to the code, several month ago. This issue should no longer exist if it ever did.
