### ISSUE TITLE
Flooring out cheap uniques from each tier

### ISSUE THREAD

**Issue by freezerain** [NeverSinkDev/NeverSink-Filter#258]
Hello!
This league I customized filter a lot and it feels good. 

In the context of uniques, there are usually 3 problems when you see too much of them
1) Boss unqiues 
2) Multibase uniques
3) Cheap uniques

So I make a preset to help me distinguish this problematic items, for example:
1) I added blue border to boss uniques and made them smaller, so I can safely skip hovering over this items when not in boss area
2) I added cyan border to multibase so I can check by icon, and not waste my time checking their rolls 
3) I add a small gold tint to leather/heavy belts border for HH/Mageblood. So I know its a gamble item and I am lookig for specifiec icon only when hovering.

on the screenshot I will hover golden items looking for HH/Mageblood/Ventors gamble, then cyan for any unusually rare icon and totaly skip blue ones because im in normal map:
![image](https://github.com/NeverSinkDev/NeverSink-Filter/assets/35431136/0be79238-8da9-4da3-a75e-1804108d9f4a)

However I cant find a way to filter out cheap uniques.

First of all I am not sure if I using this mechanism properly, I was trying to google some guides but didnt found anything similar of what I am trying to do. 
Imagine that I want to floor out all uniques cheaper then 50c. I will enter the desired price in tiering configuration window, then hit auto sort, then save it as preset, then for each filter which I want to use this preset I need to load it and save it to POE account. 
![image](https://github.com/NeverSinkDev/NeverSink-Filter/assets/35431136/a4a9e0cf-16b4-4361-88d0-6f157bda6465)

As you can see this process is not very designed to be used with presets, but even if user is okay to repeat this ritual every month or so the auto sort will hide some uniques like eye of the greatwolf amulet that can be easily cost 100d.
And even if user is ok to hide or manually adjust tiering of those highly volatile in price uniques, this mechanism will not remove cheap uniques from multibase and boss-drop tiering heres example:

If in configuration window add those tiers to autosort, it will not function because your sorting relies on the order of tiers, and multibase and boss-drop tiers are not strictly vertically lower in value, t1 will have all items from boss-drop/multibase leaving those "special" tiers completly empty (its only possible to next tier have lower or same value as previous one. boss-drop, multibase probably should be higher in tier then t1 but obviously still have "lower tier" visible imprint on the screen)
![image](https://github.com/NeverSinkDev/NeverSink-Filter/assets/35431136/da3b9d50-555a-46b0-82cd-27d09da602be)

So this is a list of obstacles I encountered trying to reach my goal: "Floor out uniques that costs less then some threshold (50c)"
1) Impossible to remove uniques by threshold from the tier, only to balance them between multiple tiers.
2) Impossible to set up new trash tier with higher priority that everything else and have it "everything LESS then 50c", which should fix this problem. 
3) If auto sorted by price presets should be created for multibase, boss-drop and the rest tiering system independently
4) When refreshing economy state user will have to load EVERY preset with auto sorting(which is atleast 3 in this case), found auto sort button to press it, save the presets, and then load EVERY filter that using those presets and finnaly save it to poe. Maybe it is difficult to automate the process but perhapse there are a way to make better UI to streamline this process of syncing between presets and filters
5) There are no way to adjust how the average item price is treated, for example eye of the greatwolf amulet, so user will have to hover over each unique and manually remove them from tiering (which I did this league) however it will be MUCH easier if UI will highlight items with expensive rolls, have some kind of "price confidence" in auto sort configuration or show "min-max" window of item. I understand that this data is provided/or not by poe ninja, and can be immposible to implement. 

This is only while talking about uniques, if user will want to filter out other categories, he will need to add more presets for each categorie + N conflicting "special" tier in the same categories. To be fair, filter out currencies and cards are simplier then uniques.

For now I am proposing to add a functionality to "collect everything LESS then" in auto sort configuration window what will made possible to create a trash custom tier and collect items from other tiers without mixing them, and add a button to "My filters" tab near each filter that will loop trough each dependent presets, and hit all auto sort buttons while saving them to their slots.

**Comment by NeverSinkDev** [comment]
I took my sweet time answering this and I apologize for the insane delay.

We definitely want to rework the economy tools available on FilterBlade. Something I'm not willing to do is create 'hotfixes' for an already poor system. I want to do it in quality and that'll likely take it's time. 

I'm currently in the process of defining requirements for the rework, but realistically this won't be a priority before PoE2 related work is done - currently by far our highest priority.

I'll definitely take the ideas from this post into consideration:
- We likely will have an economy screen where the user will be able to set up rules, update tiering and define update behaviour
- We want an easy way for users to hide out items below a certain value
- We want advanced users to be able to define more detailed behaviours
- Ideally we want the system to be module-compatible

I'm going to bookmark and close this post for now, as there won't be any short-term work done regarding this.
