### ISSUE TITLE
Just a request

### ISSUE THREAD

**Issue by llimdull** [NeverSinkDev/NeverSink-Filter#261]
There is a list of Uniques and how much Dust they give from disenchanting. 
Is there a way to made a category with maybe all uniques over 100k dust, or 50k etc. ?
![image](https://github.com/user-attachments/assets/b4e39709-1eed-4094-8fc4-75fd12cc5e7a)
Thats the val for ~100k dust
https://poedb.tw/us/Kingsmarch#Disenchant
ty hf =)

**Comment by NeverSinkDev** [comment]
What's the data source?

**Comment by llimdull** [comment]
I only know from the poedb site that you can sort by "val" and the higher the value, the more dust you get when disenchanting. Rakiata's Dance, for example, gives 1,800,000 with val 768.72 and queens hunger ~100k with a high item level with 43.48. Essence Worm with val 4.59 9,000. I don't know where poe db got that from.

**Comment by llimdull** [comment]
At the moment I have found a place where I can enter a few unique items manually. 
![image](https://github.com/user-attachments/assets/f7c00dab-e104-40e9-b092-0b7117030001)
So if nobody else wants it or hasn't even thought about it, I've found a solution, maybe complicated, but not as complicated as doing it for everyone. =)
