### ISSUE TITLE
Some Items triggering as "Overquality" even when having 0 quality

### ISSUE THREAD

**Issue by rCan9** [NeverSinkDev/NeverSink-Filter#262]
In uber Strict filter and above, Conquest Lamellar still shows as overquality drop (in game) even when it has 0 quality. Nothing in filterblade is showing it. Tested it with "Simulate->Import items from PoE" and its hidden in filterblade's simulation but still appears in game.
![Screenshot 2024-08-27 145153](https://github.com/user-attachments/assets/893e4ee2-3b9f-441e-9577-94a92276ce78)
![Screenshot (218)](https://github.com/user-attachments/assets/e5c79e31-2ddb-4ebf-9e34-4172ca043759)

**Comment by NeverSinkDev** [comment]
This has been addressed.
