### ISSUE TITLE
Gems with 6%+ quality showing ingame but simulate show as not to be shown

### ISSUE THREAD

**Issue by groch** [NeverSinkDev/NeverSink-Filter#263]
As the title said, i have a Uber strict filter based, and gems with 6%+ quality are showing and i can't find a rule to hide it

here is the copy paste of a gem that show ingame and not in the website
edit: i've put it in a pastebin so it's easier [here](https://pastebin.com/igkW13MT)

and [here is the link for my filter](https://www.filterblade.xyz/?profile=grocho&saveState=ASHUE07DQW8O1U&platform=pc&isPreset=false)

**Comment by NeverSinkDev** [comment]
This was caused by kingsmarch having an arealevel of 1 and triggering leveling gem rules.

I've since published an update to address that, should be solved
