### ISSUE TITLE
Influenced rares selection

### ISSUE THREAD

**Issue by charsz** [NeverSinkDev/NeverSink-Filter#264]
I'm farming with Scarab of apparitions for influenced rare items. I've removed rares bigger than belt. Each time there is upgrade (I think its not on load but havent tested) I'm loosing my selection. And it's a lot of clicking to revert it back to my personal selection.

**Comment by NeverSinkDev** [comment]
The tiering of influenced basetypes is sadly technically a bit more complicated and we don't support full locking of them. (yet).
This should never *remove* items you selected, but might add new ones:

What I recommend you to do:
1) 
![image](https://github.com/user-attachments/assets/31b825dd-7066-4d60-bc33-f9fae3031717)
Disable all T2 influenced bases
2) Adjust the visuals of this section: 
![image](https://github.com/user-attachments/assets/65bcf27a-388e-4f9c-9e85-f15201e87d6f)
3) Hide all remaining influenced items: 
![image](https://github.com/user-attachments/assets/5694c923-d6fc-42c3-bf0e-f1058c5bb739)

This way you'll only see influenced jewellery and the few T1 bases.
