### ISSUE TITLE
Failed to load item filter

### ISSUE THREAD

**Issue by jc9900** [NeverSinkDev/NeverSink-Filter#266]
"Failed to load Item Filter. Reason: Line 235: Unable to parse parameter for BaseType rule: No base types found exactly matching "Apex Cleaver"". I tried deleting that line or just deleting the entry "Apex Cleaver" but none worked

**Comment by TheOne320** [comment]
Just to make sure, you are using this filter with Path of Exile **1** right?

**Comment by jc9900** [comment]
Oh, i was trying to use it with poe2 lol
