### ISSUE TITLE
Unique leather belt highlighting

### ISSUE THREAD

**Issue by zocke1r** [NeverSinkDev/NeverSink-Filter#27]
Considering that it is possible for headhunters to drop, leather belts should get the same highlighting as T1 uniques.

**Comment by Exportforce** [comment]
You do NOT want every Immortal Flesh, Umbilicus Immortalis and Wurm's Molt a T1 sound. It's already mean with Tröllnir.

**Comment by NeverSinkDev** [comment]
This is going to be utterly disappointing for most players. According to what I've know a HH drops once in about ~30-40 unique leather belts and it also requires the player to run a nemesis leaguestone. 

I believe it's a bad idea.

Closed
