### ISSUE TITLE
Filter doesn't show ilvl 61-65 utility flasks!

### ISSUE THREAD

**Issue by IcySystem** [NeverSinkDev/NeverSink-Filter#30]
Title: Filter doesn't show ilvl 61-65 utility flasks!

Tested it ingame with a ilv 61 granite flask and online on FilterBlade. Something must have changed. It worked with older versions of the filter.

**Comment by NeverSinkDev** [comment]
Hey,

you're right, thanks for bringing it up, I've localized it. I'll distribute the fix in the coming patch (before 3.0 release, might make a hotfix these days).

Best Regards,
NeverSink
