### ISSUE TITLE
maps hard to find ;(

### ISSUE THREAD

**Issue by conetopia** [NeverSinkDev/NeverSink-Filter#31]
apparently im using neversinks loot filter #2 semi restricted
all maps are like very tiny text, and very hard to see... its a common white/grey text with black background
very small background too... so i end up missing half the maps...
can we change it to make the boarder/text like super huge like 7 to 10 times the size?

**Comment by NeverSinkDev** [comment]
They have a larger size than normal and make sounds upon dropping. 

Did you edit the filter? Also what areas are you running?

**Comment by NeverSinkDev** [comment]
I'll consider making the on-level maps larger.

Closed due to lack of reply/feedback.
