### ISSUE TITLE
Could you add the one hand Elegant Sword base to be shown on your item filter

### ISSUE THREAD

**Issue by ZeroCool940711** [NeverSinkDev/NeverSink-Filter#32]
Hi there, as the title says I would like to know if you could add the one hand Elegant Sword base to be shown on your item filter as it is needed for The Goddess Scorned recipe which is used for The Goddess Unleashed recipe, right now your filter hides that and other bases needed for that recipe. Thanks for your time.

**Comment by NeverSinkDev** [comment]
I might add it as an optional module to http://filterblade.xyz/ , but not to the default filter, because of the very low demand.
