### ISSUE TITLE
Uber Strict Filter Text Turns Brown

### ISSUE THREAD

**Issue by TheSixStringSamurai** [NeverSinkDev/NeverSink-Filter#33]
I don't know if I'm just really good at breaking things or if this is some problem with the automation but using only the WYSIWYG editing and the uber strict template I end up with almost every dropped item having brown text even though the filter preview and loot simulator show the correct colors.

I save the filter in the correct colors, load the game, brown text. Important the filter and almost all text is brown. Fix it again and the result is the same.

I've even gone 1 level at a time from 1 to 99 spamming in the loot simulator to find brown text, fixing it on a case by case basis, and again brown text. I'm not sure if this is the right place to provide the info for your Filterblade.xyz process but seeing as there's not really a direct feedback on the site, and it is your filter and scripts I'm trying here.

**Comment by NeverSinkDev** [comment]
Never heard of this before. Can you provide the steps, you've taken to do this? Can you recreate this? Also create a save file (not a filter) in the download menu and upload it somewhere.

**Comment by TheSixStringSamurai** [comment]
Yeah I've done it 3 times so far. Basically edit it, I've been trying remove everything but market currency, chance bases (skyforth, shavs, headhunter base), Maps/Fragments/Splinters, atlas bases (steel rings, marble amulets, crystal belts) and item level 84+ that's of value (mostly top ES bases). Everything in the simulator looked correct. Export, get into game and now everything is now brown text including currency. The only things that should have brown text are: 6 socket items, uniques, and perandus coins per my edit.

https://drive.google.com/open?id=0Bz76UivKX1QuMVFTNHpNWWFoSUU  That's most edited version (231 changes only with the visual style editor and even loading it into the site results in what I want to see, in game text goes brown).

https://drive.google.com/open?id=0Bz76UivKX1QuYlMtTW5GMTVsc28 This was my starting edit and I forgot to check levels so was showing way too much outside of level 70. It is 163 changes. It's colors looked fine, I exported it, in game brown text on currency and items, imported it back into the filterblade site and check everything is brown.

The difference between the two is the 163 is basically where this all started, the 231 me through an OCD moment going level by level from 1 to 99 and using the quick editor to fix problems as it was shown. It is where I'd like an uber strict filter to be, just not brown.

There is no code editing being done by myself this is all purely through the filterblade visual editor. 

PS: Sorry for wall of text.

**Comment by TheSixStringSamurai** [comment]
http://i.imgur.com/EiVhSPz.jpg took a side by side screenshot of the filterblade.xyz website loot simulator and what I'm getting in game.

**Comment by NeverSinkDev** [comment]
Hey,

I have good news and bad news. 

Good: We've isolated and found the bug! Thank you. It won't happen again.
Bad: Your save will still be broken
GOOD: Nevermind, Tobnac manually fixed it https://pastebin.com/wJBixUCC 

I'll leave the issue open for now. Tell me if it works for you

**Comment by TheSixStringSamurai** [comment]
Thank you guys very much, it is indeed now working as it should.

**Comment by NeverSinkDev** [comment]
Perfect, thanks!

Closed.
