### ISSUE TITLE
No sound when divine orb drops.

### ISSUE THREAD

**Issue by 2131248915** [NeverSinkDev/NeverSink-Filter#36]

**Comment by NeverSinkDev** [comment]
There is a sound. The new "shaper voice sounds" seem to be bugged. I'm reverting this and uploading the new filter in an hour.

**Comment by 2131248915** [comment]
Alright thanks.

**Comment by SimplePrimate** [comment]
Most people that don't hear those sounds have the dialogue volume turned down because they don't want to hear dialogue and for some reason the voice filter sounds are using that volume meter too
  

  
  

  
  
>
