### ISSUE TITLE
Exalted sound too quiet

### ISSUE THREAD

**Issue by adamjedlicka** [NeverSinkDev/NeverSink-Filter#38]
Dunno where else the shaper voice is used but it's too quiet. Noticed it on exalted drop and didn't hear anything.

If you can't make it much more louder, please, revert back the old sounds.

**Comment by spookyglowingbadger** [comment]
I believe this is a bug with the new positional alerts. Try dropping two different items side by side with the same alerts but one being positional and the other not. The non-positional one will be much louder even with the exact same settings.

**Comment by danidoedel** [comment]
No positional sounds are being used in this filter though.

**Comment by adamjedlicka** [comment]
It is fine when you drop it alone but in a fight when there is a lot of other sound effects it really hard to hear.

**Comment by danidoedel** [comment]
Yeah agree... in comparison chaos is much louder

**Comment by NeverSinkDev** [comment]
There is a sound. The new "shaper voice sounds" seem to be bugged. I'm reverting this and uploading the new filter in an hour.
