### ISSUE TITLE
Scrolls not showing in Semi Strict

### ISSUE THREAD

**Issue by rages4calm** [NeverSinkDev/NeverSink-Filter#39]
Scrolls will not showing using latest zip from filters in for the Semi Strict filter and the google docs says it does.

**Comment by NeverSinkDev** [comment]
It was a semi-intended change, but I forgot to announce it, which was a screwup on my side. I aplogize for that. I'm uploading a new filter version in a an hour. This one will have wisdom scrolls enabled on semistrict again.
