### ISSUE TITLE
6 socket magic items shown as rare

### ISSUE THREAD

**Issue by Jmamic** [NeverSinkDev/NeverSink-Filter#41]
http://i.imgur.com/uAX43k0.jpg

**Comment by danidoedel** [comment]
Rare would have a green background...

**Comment by Jmamic** [comment]
I see, it might not be a bug but it looks unintuitive. Everywhere else in filter rares are gold/yellor and magic items are blue so I thought this was a bug.

**Comment by NeverSinkDev** [comment]
This was indeed a visual bug. Fixed in 5.1. Thanks
