### ISSUE TITLE
Divine life flasks hidden way to early in the leveling process for regular filter

### ISSUE THREAD

**Issue by iljasuger** [NeverSinkDev/NeverSink-Filter#43]
Just checked it, and non-quality divine life flasks are hidden at zone level 61 and above. They start dropping at around zone 60, leaving a way to small window to find a few to use. I found none at all through my leveling process at the start of Harbringer. And this is using your regular filter that hides things the least.
Is this a typo, and it should be at zone level 71 and above?

**Comment by danidoedel** [comment]
Same as #42 I guess

**Comment by NeverSinkDev** [comment]
Thanks for the report. 

I'm pushing a new version in an hour. This one will have this problem fixed.

Closed
