### ISSUE TITLE
Rare RGB Items not highlighted

### ISSUE THREAD

**Issue by Exportforce** [NeverSinkDev/NeverSink-Filter#44]
Hello,

just installed the new update but found out that RGB rare items are not highlighted.
Happend for me on this item (screenshot can be attached if needed):

Rarity: Rare
Headman's Sword
--------
Two Handed Sword
Physical Damage: 47-109
Critical Strike Chance: 5.00%
Attacks per Second: 1.30
Weapon Range: 11
--------
Requirements:
Str: 106
Dex: 89
--------
Sockets: R-G-B 
--------
Item Level: 70
--------
+400 to Accuracy Rating
--------
Unidentified

**Comment by PiotrPodsiadly** [comment]
Which version of the filter are you using? Regular/Strict/Uber
It is item level 70 and takes 8 inventory space. While mapping it may be considered not worth picking up.

**Comment by Exportforce** [comment]
Hello,

I am using "Regular". As you can see from the description of the item being called "Two Handed Sword", yes it is a large item.

**Comment by NeverSinkDev** [comment]
This is somewhat intended.

The filter syntax makes it complicated to evaluate a rare by it's color-combination and all the other properties, without bloating the filter with exceptions - which will affect size, performance and update safety. 

It was a design decision to prioritize it's properties as a rare over it's qualities as a potential chromatic item. - especially considering the fact that big items are innefficient pickups and small ones usually end up being picked up anyway.
