### ISSUE TITLE
Filter REGULAR hides level 60 flasks?

### ISSUE THREAD

**Issue by Ancient3** [NeverSinkDev/NeverSink-Filter#47]
Hello,

why does the "1-REGULAR" filter (v5.0.1) hide normal "Divine Flasks" (level 60) that are around my level of 60-70? The filter didn't seem to do that with previous flask tiers? Even normal ones were highlighted in a bigger font.

Regards.

**Comment by danidoedel** [comment]
Maybe because 5.1 fixed this and we are already on 5.1.1?

**Comment by Ancient3** [comment]
Yes, I didn't find it previously in the changelog:

"Divine/Eternal flasks are now shown for a longer time. They're now also visible in low tier maps on the regular/semi-strict version."
