### ISSUE TITLE
Fingerless gloves

### ISSUE THREAD

**Issue by seatthief** [NeverSinkDev/NeverSink-Filter#49]
Blue unid'd Fingerless silk gloves ilvl84 with 14%implicit spell dmg show up with orange border and text (as if it was a unique item) on the strict version of the filter.

**Comment by dein0s** [comment]
Atlas-exclusive crafting base, color differs from unique.
Everything working as intended.
You can change this colors by yourself in [Filterblade](http://www.filterblade.xyz/): `Customize -> Special Bases and Rules -> Atlas-exclusive`

**Comment by NeverSinkDev** [comment]
ilvl 84 atlas bases are fairly rare, usually sell for at least a bit and are good crafting bases. As @dein0s said, you can customize that behaviour and their appearance on FilterBlade. 

There's no issue here.

Closed
