### ISSUE TITLE
Small RGB Gemstone Sword not properly highlighted

### ISSUE THREAD

**Issue by Exportforce** [NeverSinkDev/NeverSink-Filter#50]
http://prntscr.com/gbckxv

As you can see a small 3 square item RGB linked is not properly highlighted.

**Comment by NeverSinkDev** [comment]
This behaviour is (somewhat) intended. RGB highlighting rares would significantly increase the size of the filter and cause some confusion in terms of tiering/priorization. I might implement a workaround, but currently I don't highlight rares by RGB links.
