### ISSUE TITLE
Ambusher is missing from FilterBlade auto-complete feature for uniques.

### ISSUE THREAD

**Issue by LaplaceNoMa** [NeverSinkDev/NeverSink-Filter#51]
It's present for rares, but if trying to add it in 'uniques' section, it shows 'Invalid/Incomplete name, click again to confirm!'

**Comment by NeverSinkDev** [comment]
Hey, 

we've added those to FilterBlade internally, it'll be part of the next patch (eta 1-2 weeks).

Thanks.
