### ISSUE TITLE
Shaped maps not notifying as correct tier

### ISSUE THREAD

**Issue by mrmonday56** [NeverSinkDev/NeverSink-Filter#52]
Had a shaped Flooded Min drop (tier 2 -> tier 7) in a tier 7 map but it did not make the sound nor have the outline for a tier 7 map using purple semi-strict

**Comment by NeverSinkDev** [comment]
Fixed in 5.41 - check for details 
 https://www.reddit.com/r/pathofexile/comments/7ixsxf/neversinks_itemfilter_version_541_shaped_map/
