### ISSUE TITLE
semi strict 4link sound no longer needed

### ISSUE THREAD

**Issue by marat569** [NeverSinkDev/NeverSink-Filter#53]
Currently Semi-Strict plays a sound for all 4 link drops. While useful at league start, I don't believe it is something that should be in semi-strict at the current state of the league. 

I know swapping to strict is always an option, but I prefer to stay on semi strict for now for a few reasons.

TL;DR: Keep the border, remove the sound c:

**Comment by NeverSinkDev** [comment]
This sound is only happening, while leveling (<65) and the sound is used exclusively for leveling items (rare rings/amulets, useful utility flasks, 4links).

I don't think that removing it from semi-strict is the elegant choice here.

I'm currently thinking about limiting it to ilvl 40-45 though.

Also: You can always configure it on www.FilterBlade.xyz

**Comment by marat569** [comment]
For leveling I agree, but I was farming blood aqueducts, was level 60+, and still heard dings for all the 4 links, utility flasks, etc.

40-45 would be perfect. You can keep the border/color/size of utility flasks, but not the sound.

Also with the price of biscos, a quick suggestion would be to have base gold amulets to be soundless with a border by default in most filters; similar to how leather belts where in 3.0. For strict I had to manually uncomment the entry. I'm not sure when you stopped showing leather belts in 3.0, but that would be a good base line for gold amulets.

**Comment by SimplePrimate** [comment]
You can change it yourself on filterblade.com
  

  
  

  
  
>

**Comment by SimplePrimate** [comment]
ilvl 45 would probably work better, especially for semi strict and strict   
  

  
  

  
  
>

**Comment by SimplePrimate** [comment]
Ya I agree on semi strict and strict that 45 would be better, I just went and changed it. I always use strict with around 15 or 18 changes that suits me   
  

  
  

  
  
>

**Comment by NeverSinkDev** [comment]
In 5.42 the sound is disabled on Semi-Strict and higher versions.

Closed.
