### ISSUE TITLE
Stygian vise rarity

### ISSUE THREAD

**Issue by tuxmaniac** [NeverSinkDev/NeverSink-Filter#56]
https://github.com/NeverSinkDev/NeverSink-Filter/blob/db282b69afe603765939301bcfe5afba11096a0f/NeverSink's%20filter%20-%206-UBER-PLUS-STRICT.filter#L377

Add condition `Rarity <= Rare` into section `%TB-Vise %H5`

Now unique stygian vise belt handled by this block and hidden in uber-plus-strict version

**Comment by NeverSinkDev** [comment]
Fixed in 5.43
