### ISSUE TITLE
5L 6S Chestpiece shows 5L colors

### ISSUE THREAD

**Issue by MercerK** [NeverSinkDev/NeverSink-Filter#58]
I found this during the races, but didn't screenshot it. I encountered it again and wanted to screenshot it.

This chestpiece is a 5L 6S, but shows the 5L rule. https://imgur.com/s2DnXdu

Is this intended or should it show the 6S rule instead?

**Comment by NeverSinkDev** [comment]
5L rule currently has higher priority. I'll see if I can make a combined rule or something over time

Closed.
