### ISSUE TITLE
No high level Spirit Shield bases

### ISSUE THREAD

**Issue by AngryRoleplayer** [NeverSinkDev/NeverSink-Filter#59]
![2017-12-26_9-32-0 111](https://user-images.githubusercontent.com/22470478/34349047-c4b1277e-ea1f-11e7-9e00-25d484354b65.jpg)
Where are they?
![2017-12-26_9-32-28 223](https://user-images.githubusercontent.com/22470478/34349043-bfc65658-ea1f-11e7-8a2e-296f81db9c34.jpg)
How can i  highlight ALL spirit shields now?

**Comment by NeverSinkDev** [comment]
Not exactly a bug.  You can type in "Titanium" or another name and you'll find the shield, the problem is the limited auto-complete size. I'm not sure if and when we'll be address it, but I'll note it down.

Thanks. No high priority for now though.

**Comment by AngryRoleplayer** [comment]
maybe you can just put high level bases there instead of low-level bases.

**Comment by NeverSinkDev** [comment]
I can't "just" do it.

I'd have to either remove the low level items from the database, which is an absolute no-go or introduce and additional sorting layer.

This approach is better, but will cost performance and kill alphabetic sorting.

Both approaches are ugly. I'd rather add a scroll bar/selection feature, next time we need to change something important in that Nicky

**Comment by AngryRoleplayer** [comment]
I see, well, the only reason why i posted this is because these bases were there before, but were removed for other purposes i guess :)

**Comment by NeverSinkDev** [comment]
They're still there.

We previously used a different auto complete system. It had some upsides, but was horribly laggy and buggy at times. During one of our latest patches, we replaced it. This one is much better, but still needs some fine tuning. Currently it's limited to 5 items/autocomplete.
