### ISSUE TITLE
necromancy net

### ISSUE THREAD

**Issue by Ardolo** [NeverSinkDev/NeverSink-Filter#64]
![net](https://user-images.githubusercontent.com/37174179/37140921-067a41a2-22bc-11e8-9353-454b99879657.jpg)
some feedback 
NeverSink-Filter-5.62beta

**Comment by NeverSinkDev** [comment]
I'll implement them once I'm home. (eta 9 hours)

**Comment by shot0829** [comment]
its naming error.
change "Necromancer"
to "Necromancy Net"

**Comment by NeverSinkDev** [comment]
Fixed
