### ISSUE TITLE
Low tier nets making a noise when hidden

### ISSUE THREAD

**Issue by Synol** [NeverSinkDev/NeverSink-Filter#65]
Not sure what is causing this, low tier nets are making a sound when dropping, there is no sound set in the code for them:

Hide  #$Currency->Net->T3
Class  Currency
BaseType  "Simple Iron Net" "Reinforced Iron Net" "Strong Iron Net"
SetFontSize  42
SetTextColor  155 210 135 255
SetBorderColor  110 110 110 255
SetBackgroundColor  0 0 0 255

**Comment by NeverSinkDev** [comment]
This is the default sound. I have no control over it and can't disable it.

GGG is aware of the issue.

Closed.
