### ISSUE TITLE
Missing Stone Hammer [etc.] highlightning 

### ISSUE THREAD

**Issue by BudSpanker** [NeverSinkDev/NeverSink-Filter#66]
Hello there,

since Abyss league I'm missing the highlightning of stone hammers, rock breakers and gavels for the cartographers chisel recipe.

The code is written in the lootfilter but nothing shows up when I'm playing. Just from time to time I press ALT for checking the blended out stuff I see (with luck) a hammer or if the hammer is rare with yellow background color.

I'm using the semi-strict filter btw.

best regards,

**Comment by NeverSinkDev** [comment]
Not a bug. 
Low Quality (<15) stone hammers are disabled on semi-strict. You can use www.filterblade.xyz to edit/adjust this easily.

**Comment by BudSpanker** [comment]
Thanks for the hint! I was already struggling with editing the filter file by text *g*

keep the great work up!

best regards,
