### ISSUE TITLE
Very Strict - Hides IMPRINTS

### ISSUE THREAD

**Issue by PJP2810** [NeverSinkDev/NeverSink-Filter#67]
Picked it up and so can't test for other strictnesses, however the Very Strict #4 variety of the filter hides Imprints that come from the beast crafts. Which by default drop to the floor.

**Comment by NeverSinkDev** [comment]
Good point, I've never thought of imprints as "dropables" before. I'll fix it in the upcoming patch.

**Comment by NeverSinkDev** [comment]
Fixed in latest version. Thanks! 

Closed
