### ISSUE TITLE
Attack-based Leveling presets on filterblade.xyz should show Rustic Sash throughout leveling

### ISSUE THREAD

**Issue by ogier** [NeverSinkDev/NeverSink-Filter#68]
While leveling, especially at league start or in races, a steady supply of Rustic Sash items is useful for the X% Increased Physical Damage vendor recipe. The ilvl matters, so it's not enough to just hold onto some early Sashes, it's better to pick up a white one shortly before you use the recipe so they should always be visible while leveling.

I think it makes sense to put this behind the Leveling preset options related to attacks. All weapon types used in attacks can use this recipe.

As a side note, probably these attack leveling presets should disable Handpicked: Act 1 and Handpicked: Acts 2, 3 Caster Weapons rules, and the Rares: Caster Weapons rule since there's no reason to call out wands etc. while leveling as an attack build.

**Comment by NeverSinkDev** [comment]
Thanks, I'll consider it.

I will likely rework all the presets for 3.3 or at least soon after.

**Comment by NeverSinkDev** [comment]
Done
