### ISSUE TITLE
Double Actions in release 6.0a

### ISSUE THREAD

**Issue by LordBlick** [NeverSinkDev/NeverSink-Filter#70]
Mentioned 0 - SOFT from main folder for reference.
I found some inconsistencies, are these intentional?:  
 - double `SetTextColor` in  lines 1977/1978 and 1986/1987  
- double `SetBorderColor` in lines:  
  - 4148/4149  
  - 4158/4159  
  - 4176/4177  
  - 4187/4188  
  - 4206/4207  
  - 4217/4218  
  - 4236/4237  
  - 4247/4248  
  - 4266/4267  
  - 4277/4278  
  - 4296/4297  
  - 4307/4308  
  - 4326/4327  
  - 4337/4338  
  - 4356/4357  
  - 4367/4368  
  - 4386/4387  
  - 4397/4398  
  - 4416/4417  
  - 4427/4428  
  - 4446/4447  
  - 4457/4458  
  - 4475/4476  
  - 4485/4486

**Comment by NeverSinkDev** [comment]
Thank you, I'll fix this in the upcoming update this week.

**Comment by NeverSinkDev** [comment]
fixed
