### ISSUE TITLE
Release 6.0a: All gems displayed in large text and play drop sound

### ISSUE THREAD

**Issue by dmarchand** [NeverSinkDev/NeverSink-Filter#71]
As of 6.0a, in filter STRICT, everything in Item Classes: Gems plays a drop sound and displays in large blue text.

**Comment by dmarchand** [comment]
This actually appears to be a weird interaction between Filtration and 6.0. Looking into it more.

**Comment by NeverSinkDev** [comment]
This is likely caused by filtration having troubles with the new GemLevel commands and not saving those. 

I recommend contacting the filtration dev or using filterblade.

Closed.
