### ISSUE TITLE
Font size not working

### ISSUE THREAD

**Issue by Question2** [NeverSinkDev/NeverSink-Filter#72]
I have custom "highlight items by slot" rules in the "end game level 65+" section, but the font size is very small. I have tried changing the font size multiple times, but the game always displays the font size in a very small font size, much smaller than the font size used for orb of alterations.

I maxed out the font size at 45 but there is no difference, the font size does not change at all. The font size displayed on the filter customizer's simulate page is correct, but it does not work ingame.

This is font size 45 but the game is displaying it as really small for some reason.
![poe8](https://user-images.githubusercontent.com/1191378/41052509-449e0f90-69fc-11e8-9d68-f67e81974761.jpg)

**Comment by NeverSinkDev** [comment]
The font sizes are enlarged on the website for better editing and mobile visualization.

The font size 45 IS the maximum font size and IS used by alterations for easy pickup.
