### ISSUE TITLE
Syntax highlighting colors used for POE filter in the VScode

### ISSUE THREAD

**Issue by explooosion** [NeverSinkDev/NeverSink-Filter#73]
Hello @NeverSinkDev 

Thank you very much for sharing with us your filters. ❤️

[POE Filter](https://marketplace.visualstudio.com/items?itemName=robby.poe-filter) is my extension for  [VS Code](https://code.visualstudio.com/).

### Demo
![image](https://user-images.githubusercontent.com/13682994/41188870-bb6aa442-6bf7-11e8-93e6-d2a79e3850f6.png)

I hope it helps you. 🙂

**Comment by LordBlick** [comment]
Is this an issue? I appreciate your work, but it is inappropriate place…
