### ISSUE TITLE
Bug, making Rare Abyss Jewels hidden when reloading your changes into FilterBlade

### ISSUE THREAD

**Issue by TreeRipper** [NeverSinkDev/NeverSink-Filter#75]
So i saw on the forum's that reporting Bugs with FilterBlade here was the way.
The issue happens when loading your filter from the cookies in Google Chrome.

Open website -> save&load tab -> load the desired filter from the list -> check abyss items submenu

For me every time i reload a filter (and it's not one that needs to ge through the update of a new version of
FilterBlade) the rule for rare abyssal jewels (below ilvl 82) is set to hide.

**Comment by Tobnac** [comment]
Can you provide a saveState (like a sharing link or the saveFile) or more info to reproduce this bug?

**Comment by TreeRipper** [comment]
For sure, this is the save file, i have continously edited it from 3.1 onwards and it went through more than 20 iterations. Well i think there is not much more to say about the reproduction than i already have, i see something i want to change, open the website, load it from the cookies, switch some stuff around and save it. Im kinda paranoid so i check the hidden items with ALT sometimes ingame, when i do that i see rare abyss jewels on the floor (same thing happens to T2 rare SMALL 2x2 armour items) and go back to the page to adjust it. At frist i thought it was my mistake but i can now with high confidence say that it happens everytime

[FilterChanges_3.3 Sixth Iteration.txt](https://github.com/NeverSinkDev/NeverSink-Filter/files/2108871/FilterChanges_3.3.Sixth.Iteration.txt)

If you need anything else let me know, i could even record it when it happens if that helps.

**Comment by Tobnac** [comment]
[FilterChanges_3.3.Sixth.Iteration_fix.txt](https://github.com/NeverSinkDev/NeverSink-Filter/files/2108952/FilterChanges_3.3.Sixth.Iteration_fix.txt)

I found and fixed this one error in your saveState. Right now its still on Hide, but when you now set it to Show it will stay like that. I also found the origin of the bug (which is a small incompatibility between old and new methods) and will see if I can prevent this from happening for other cases with those older save states.

**Comment by Tobnac** [comment]
Nope, I just fixed the Abyss Jewels atm. Fixing the rares is a bit more complicated and I'd rather spend that time on fixing that bug for good instead of just fixing single instances of it, so that you can later just load the save on the live FilterBlade and it will fixed automatically.

**Comment by TreeRipper** [comment]
Sounds great! Is this the first time somebody pointed this out? Also i wanted to thank you guys for the fantastic work you are doing with the website, the basic stuff is  very accessible and more advanced stuff can still be set if you know where to look. Having a filter that suits your playstyle is very important for efficient play and you enable everyone to achieve that, so keep it going!

**Comment by Tobnac** [comment]
Thanks a lot, you're welcome :)

and yeah, you were the first to point out that bug. But its a rather special one that only happened when you had a saveState in which you edited rules on the simulate-tab, which were also handled on the customize tab and you had to do have done those a few months ago....special stuff like that :P 
So I'm not surprised youre the first one on that topic!
