### ISSUE TITLE
Style Variation Description needed.

### ISSUE THREAD

**Issue by KingKatura** [NeverSinkDev/NeverSink-Filter#76]
Loving the new Vaal Style and can't wait to try the Velvet style. But I noticed a description text was missing for Vaal and velvet styles under Style Variation, I was going to add it for you. Then realized i could not. So instead for the new users or old who are scared of change adding this 5 minute description will probably get more players to try it out. This in turn will Influence you to keep on making the game better by changing in the ways that you do, so that we are never left with the same dull thing over and over again.

**Comment by NeverSinkDev** [comment]
I'll try to add those and see if I can make a Video too over the next days.

If you want to contribute a description or screenshots feel free to email me or add them to the wiki ( you can edit the wiki or issue a pull request ).

Thanks
