### ISSUE TITLE
Is there a way to paste multiple "types" into a category?

### ISSUE THREAD

**Issue by xerance** [NeverSinkDev/NeverSink-Filter#77]
Hey, is there a faster way to add multiple "types" or "bases" to a filter option in bulk?

for example assuming I wanted to make a custom highlight of these specific bases

Titan Gauntlets
Slink Gloves
Vaal Gauntlets
Murder Mitts
Dragonscale Gauntlets
Crusader Gloves
Arcanist Gloves
Sorcerer Gloves
Ancient Gauntlet

Instead of adding em one by one as in the screenshot below, is there a way we can add them as a bulk paste of text?

![image](https://user-images.githubusercontent.com/16266200/41523726-523b153e-72db-11e8-8964-de52c64e3bca.png)

Sorry if I asked something obvious.

**Comment by NeverSinkDev** [comment]
You can split them by comma and paste them as a single string.

Email or ask in discord next time, this is not a reason to open an issue.
