### ISSUE TITLE
Useful .gitignore.

### ISSUE THREAD

**Issue by Freydal** [NeverSinkDev/NeverSink-Filter#79]
I 'Sink' the repo directly in the necessary folder.  Some game options save files are also in the directory.  It  would be really nice if we could have a .gitignore added with the following:

`
Countdown/
MOTDCache/
Minimap/
ShopImages/
productionConfig.ini
`

Thanks for any feed back or consideration.

**Comment by NeverSinkDev** [comment]
I don't see why not, I'll add it in the next commit.
