### ISSUE TITLE
Version 6.02 and 6.1

### ISSUE THREAD

**Issue by iaai0110** [NeverSinkDev/NeverSink-Filter#80]
My copy of the filter (regular) does no deal with the chisel hammers properly. Only the gavel comes up periodically when it has x amount of quality. Both of the other two never show up on drops.

When I first started using your filter, it was formatted with <CR>'s after each line. Now it is formatted as one sentence for the entire document or filter. Is there any way that I can get a proper formatted copy in order to edit it or read it? Or do I need to use some special editor but not "edit" or "notepad" any more.

Other than this issue, it appears that your filter is great. Kudos! Of course, I have also not seen any mirrors or the new special vials so I cannot tell if that part is working. lol

Also, one other point that I would like to add: The sound that is made when a map is dropped -- this is the same sound as one of those exploding flame balls that can kill almost anyone depending on the map mods and your build. I have to run away to avoid dying but when I run away from a map drop, that is embarrassing.

Regards,
iaai0110

**Comment by dawikur** [comment]
Open it with program like notepad++(https://notepad-plus-plus.org/download/v7.5.7.html)
not with normal notepad - this will show multiple lines.

**Comment by NeverSinkDev** [comment]
Hey, 

as @dawikur said, you should open the filter with NotePad++ or a similar app.

The regular filter hides no-quality Chisel-hammers. The game has become way too fast for that recipe. 

You can also use [www.filterblade.xyz](www.filterblade.xyz) to customize and preserve changes.

The sound has a few similarities, but after hearing it a few times you'll be able to distinguish those very easily.

**Comment by iaai0110** [comment]
Thank you very much. My download speed is now 50-90 MBps or 500-900 Mbps,
so I shouldn't have any problems with the chisel hammers displaying.
Dunno UNIX style. Also, now that I know that Notepad ++ works, I shouldn't
have any problem editing it myself.

Regards and thanks again.

*"Share information to increase knowledge"*
*"Those who ask a question are stupid for thirty seconds. Those who never
ask are stupid for life. lol*
