### ISSUE TITLE
6-socket rarity not showing

### ISSUE THREAD

**Issue by ColdFaith** [NeverSinkDev/NeverSink-Filter#82]
Hi, 
i don't know if it is intendet, but the rarity of 6-socket items in not showing. 

Greets,
Tim.

**Comment by NeverSinkDev** [comment]
I'd say it's a feature, not a bug, becuase the visuals look good, but it's actually not intended. 

I'll look into it, thanks.

**Comment by NeverSinkDev** [comment]
Currently treated as a feature. 

Closed until 4.5
