### ISSUE TITLE
Add global mod to turn sound alerts into positional sound alerts

### ISSUE THREAD

**Issue by haasn** [NeverSinkDev/NeverSink-Filter#83]
In the "advanced" section of filterblade it would be nice to have an option to make all sound alerts positional. I normally just manually do this by searching and replacing after downloading the filter, but an option would be cool.

**Comment by Tobnac** [comment]
This one could be a bit more complex than the other Quick Functions on there (depending on how "pretty" we want to make that solution), but I definitely added this to our ToDo list and will look into it soon!

**Comment by Tobnac** [comment]
We just added this, as well as a Quick Function for maximizing all map icons.
