### ISSUE TITLE
Filter Not Loading Due to Sound File

### ISSUE THREAD

**Issue by livejamie** [NeverSinkDev/NeverSink-Filter#87]
This is using the Mathil sound pack:

![image](https://user-images.githubusercontent.com/49513/45063006-8e90bf80-b060-11e8-8f98-e4073fa341bc.png)

Line 3115: Invalid sound filepath "Mathil_12leveling.mp3"

This file isn't included when you download from Filterblade.

**Comment by livejamie** [comment]
Happens with Veskara too, I assume all the packs are broken

![image](https://user-images.githubusercontent.com/49513/45063187-969d2f00-b061-11e8-9ee7-2c5d00bd75bb.png)

**Comment by Tobnac** [comment]
Did you download those using the "Download all strictness" button? If yes, then we're already aware of this bug and will fix it soon.

**Comment by Tobnac** [comment]
We just deployed a fix for this

**Comment by Feracitus** [comment]
i'm getting this same bug with the gollum filepack right now. how do i fix this?

**Comment by Syrasha** [comment]
As someone who is also having this problem, it would be swell to see "how to fix" addressed here. 
My issue isn't related to having downloaded "Download all strictness" so the bug fix is irrelevant to my situation
I'm figuring it out, but it would have been real nice to have some solid advice listed here =)
