### ISSUE TITLE
Leveling rares are not correctly hidden

### ISSUE THREAD

**Issue by coffeecrank** [NeverSinkDev/NeverSink-Filter#89]
I got a weird issue and am wondering whether I'm just doing something wrong. I'm using a very strict template (which has basic progression turned off by default) and also disabled all leveling rares (see https://imgur.com/a/q6sS01h for details). However, if I do that, I still see low-level rares. You can check it at the loot simulator here: http://filterblast.oversoul.xyz/

The only solution to this was to also add extra rules and hide gear by slot. I feel like this is either not clearly explained or it's a bug.

Link to the version that has this issue (no custom rules added): http://www.filterblade.xyz/#gsCwpIavNwuz

**Comment by NeverSinkDev** [comment]
The Customizer for rare leveling items currently doesn't feature all leveling rare sections. This might happen at one point, once I find a good adequate solution to mapping them, but currently it'll stay that way.

We'll add a description for that.
