### ISSUE TITLE
Consistent file names

### ISSUE THREAD

**Issue by nCrazed** [NeverSinkDev/NeverSink-Filter#9]
The current filter file (re)naming convention breaks symbolic links. Have you considered keeping the filter file names un-versioned? 

i.e. `NeverSink's filter - REGULAR.filter` instead of `NeverSink's filter 4.21 - REGULAR.filter`.

This would allow the following setup for the users of your filters:

Have a clone of this repository somewhere on their system and create symbolic links of the `.filter` files in their PoE directory. When a new version comes out, the user simply has to run `git pull` to get the changes applied to the game.

**Comment by Net-burst** [comment]
I can second that request. I also think its a good idea to strip version from filename.

**Comment by NeverSinkDev** [comment]
There's just one reason, why I haven't done it yet:

I receive a lot of questions/problems/suggestions and in 50% of all cases the first questions I ask is: "what version are you using"/"are you using the latest version". Putting the version name into the file causes a surprising amount of confusion.

I know this requires a few more clicks for GIT-users, but I don't think the overhead is too tragic + is it possible to use wildcards?

**Comment by danidoedel** [comment]
Would `git log --follow` help in that case? Never tried that though...

**Comment by nCrazed** [comment]
> I know this requires a few more clicks for GIT-users, but I don't think the overhead is too tragic + can't you use wildcards to pull all/new files?

The point in my example is that there's no need to deal with any new files. The symlink in the game directory is always pointing to the latest downloaded (via `git pull`) of the chosen filter type.

> I receive a lot of questions/problems/suggestions and in 50% of all cases the first questions I ask is: "what version are you using"/"are you using the latest version". Putting the version name into the file contents only causes a surprising amount of confusion.

Ok, this makes sense.

**Comment by nCrazed** [comment]
@danidoedel yeah, that could be used to track the file changes. Combining that with a `post-merge` hook would allow automatic in-game update on `git pull` similar to what I wanted with symlinks.

**Comment by dein0s** [comment]
Still naming is a pain if you fork with rebase on upstream in pair with symlink :(

**Comment by NeverSinkDev** [comment]
I've been thinking about this:

I decided to keep the version name the same. This has the additional advantage, that it'll keep a proper changelog/diff versions between each version.

So yeah: starting with the next version that'll be done and you guys can update using git pull once again.

**Comment by nCrazed** [comment]
> So yeah: starting with the next version that'll be done and you guys can update using git pull once again.

Symlinks got broken again because of the ordering prefixes :(
