### ISSUE TITLE
Stone Hammers hidden after certain progression [regular]

### ISSUE THREAD

**Issue by Bzzz** [NeverSinkDev/NeverSink-Filter#90]
Finally realized this in the Bazaar map with a known drop spot - Stone Hammers (and the like) for the chisel recipe are hidden in the regular filter after certain levelling progression, I don't think that should be the case. I know that this recipe is considered a waste of time by some people, but in SSF that's a serious source for chisels in the wild. As long as the a filter shows abundant blue crap in the end game, I think white hammers should not be completely hidden. RGB items are always shown, at a price of 16 chrom/C at the moment.

**Comment by NeverSinkDev** [comment]
I'll reenable ALL hammers to be shown on soft/regular again in the next version.
