### ISSUE TITLE
RGB-linked items 1x4 have no rules

### ISSUE THREAD

**Issue by Araxyllis** [NeverSinkDev/NeverSink-Filter#92]
<=1x3 
<=2x2
and
">=2x4"
all have rules but these exclude 1x4 which are ignored completely. Seems not intended, thought i let you know

**Comment by EndlessCheng** [comment]
It seems that [this line](https://github.com/NeverSinkDev/NeverSink-Filter/blob/master/NeverSink's%20filter%20-%201-REGULAR.filter#L4857) should be removed.

**Comment by Tobnac** [comment]
Ah, in the leveling rules...Yep, fair point, this does look wrong. We'll have this fixed in the next update. Thanks!

**Comment by NeverSinkDev** [comment]
Fixed in 6.5 (to be released in ~28 hours).

Closed
