### ISSUE TITLE
"Lava Chambers Map" is wrong base type

### ISSUE THREAD

**Issue by ColdFaith** [NeverSinkDev/NeverSink-Filter#95]
Hi, 
i want to highlight "Lava Chamber Map". 
When i do this, the filter does not load, because "Lava Chambers Map" is a wrong base type. If i manually remove the "s" from "Chambers" everthing is fine. 

I think there is just a typo in filterblade, because ingame the map is also called "Lava Chamber Map" without the "s". 

Cheers,
Tim.

**Comment by NeverSinkDev** [comment]
Thanks, we'll fix it!

**Comment by Tobnac** [comment]
Fixed in FilterBlade version 0.9.9a (released just a few hours ago)
closed.
