### ISSUE TITLE
Not sure if intended (doesn't seem like it)

### ISSUE THREAD

**Issue by babis8142** [NeverSinkDev/NeverSink-Filter#97]
but some of the items hidden show up as blue when holding alt. Here is a screenshot of what I mean.

[link to steam image](https://steamuserimages-a.akamaihd.net/ugc/951846889657764925/25BED8C4263981A75CFAAB8C38DB15D15443CE5C/?imw=1024&imh=576&ima=fit&impolicy=Letterbox&imcolor=%23FFFFFF&letterbox=true)

I'm using strict azurite filter

**Comment by Tobnac** [comment]
This just looks like a usual rare item in the new azurite style to me. Some items, when they're hidden, still keep their usual colors/sizes. Not all of them become tiny white/back items.

**Comment by babis8142** [comment]
No it is still there. [Here](https://i.imgur.com/tddPFUD.jpg) is another screenshot. My cursor points to the "blue" occultist vestment in the middle of loot and you can see it's actually rare not magic
