### ISSUE TITLE
Chromatic Orb 1x3 shows 1x4 too

### ISSUE THREAD

**Issue by totaemoeggerli** [NeverSinkDev/NeverSink-Filter#98]
Vendor recipes chromatic orb small (1x3) shows 4x1 items too.
They should be excluded for this option and only be displayed with medium (2x3 and 1x4).

**Comment by NeverSinkDev** [comment]
Hey, this is currently intended. 1x4 items have become a much more compact format than they once were with all the new 1x1 items the game drops.

I'll adjust the descriptions and maybe add a way to customize it. 

Thanks!
